// Paie — les textes, en français et en anglais.
//
// La langue suit celle du système (réglage « Langue et région », automatique
// par défaut : celle que le navigateur annonce). Le bulletin imprimé, lui,
// reste en français : c'est la langue légale en Côte d'Ivoire, et celle que
// lisent la CNPS, la DGI et l'inspection du travail.

export const TEXTES = {
  fr: {
    appNom: "Paie",
    verrou: "Connectez-vous pour établir la paie.",
    grpSuivre: "Suivre",
    grpPreparer: "Préparer",
    grpPayer: "Payer et déclarer",
    grpReglages: "Réglages",
    navCycle: "Cycle du mois",
    navVariables: "Éléments variables",
    navBulletins: "Bulletins",
    navPaiement: "Paiement et déclarations",
    navReglages: "Barèmes et rubriques",
    moisDePaie: "Mois de paie",
    langue: "Langue",
    langueAuto: "automatique (système)",
    actualiser: "Actualiser",
    retourCycle: "Cycle du mois",

    // Cycle
    titreCycle: "Paie {deMois}",
    sousCycle: "Versement le {date} · {n} salarié(s)",
    sousCycleJ: "Versement le {date} · dans {j} jour(s) · {n} salarié(s)",
    simulateur: "Simulateur brut ↔ net",
    continuerVariables: "Continuer : éléments variables",
    etape_variables: "Éléments variables",
    etape_controles: "Contrôles",
    etape_validation: "Validation",
    etape_paiement: "Paiement",
    etape_declarations: "Déclarations",
    detVariables: "{prets} / {total} bulletins préparés",
    detControles: "{n} action(s) requise(s)",
    detControlesOk: "Aucun point bloquant",
    detValidation: "Par la gérance",
    detValide: "Validée le {date}",
    detPaiement: "Banque, Mobile Money, espèces",
    detPaye: "Payée le {date}",
    detDeclarations: "CNPS, ITS, FDFP, CMU",
    detDeclare: "Tout est déclaré",
    kpiBrut: "Masse salariale brute",
    kpiNet: "Net à verser",
    kpiCout: "Coût employeur",
    kpiEffectif: "Effectif",
    aideBrut: "{ecart} par rapport au mois précédent",
    aideBrutNeuf: "Premier mois de paie",
    aideNet: "Virement {v} · Mobile Money {m} · espèces {e}",
    aideCout: "dont {c} de charges patronales",
    aideEffectif: "{entrees} entrée(s) · {sorties} sortie(s)",
    actionsRequises: "Actions requises · {n}",
    actionsAide: "La paie ne se valide pas tant qu'un point rouge reste",
    aucuneAction: "Rien à signaler : la paie peut être validée.",
    salariesDuMois: "Salariés du mois",
    rechercher: "Rechercher…",
    colSalarie: "Salarié",
    colPoste: "Poste",
    colBrut: "Brut",
    colNet: "Net à payer",
    colEcart: "vs mois préc.",
    colStatut: "Statut",
    nouveau: "nouveau",
    st_pret: "Prêt",
    st_verifier: "À vérifier",
    st_bloque: "Bloqué",
    st_entree: "Entrée",
    st_sortie: "Sortie",
    echeances: "Échéances",
    echVersement: "Versement des salaires",
    echVersementDet: "Ordre de virement à préparer la veille au plus tard",
    echDeclarations: "CNPS, ITS et FDFP {deMois}",
    echDeclarationsDet: "Montants calculés à la validation",
    echDisa: "DISA {annee}",
    echDisaDet: "Déclaration annuelle des salaires à la CNPS",
    echFait: "Fait le {date}",
    masseSixMois: "Coût employeur sur 6 mois",
    masseAide: "Brut + charges patronales + CMU + FDFP",
    aucunSalarie: "Aucun salarié à payer ce mois-ci. Les fiches viennent de l'application Ressources humaines.",
    preparerTout: "Préparer tous les bulletins",
    valider: "Valider la paie",
    validerTitre: "Valider la paie {deMois} ?",
    validerMessage: "{n} bulletin(s) seront figés : net total {net}.",
    validerDetail: "Après validation, une correction passe par la réouverture du mois (administrateurs).",
    validerAttention: "{n} point(s) d'attention restent ouverts.",
    validee: "Paie {deMois} validée",
    valideeMsg: "{n} bulletin(s) figés, prêts à être payés.",
    rouvrir: "Rouvrir le mois",
    rouvrirTitre: "Rouvrir la paie {deMois} ?",
    rouvrirDetail: "Les bulletins redeviennent modifiables. Ceux déjà remis aux salariés devront l'être à nouveau.",
    moisValide: "Paie validée le {date}{par} : bulletins figés.",
    moisPaye: "Paie payée le {date} : bulletins figés.",

    // Contrôles
    ctrl_sansMatricule: "{nom} — pas de matricule",
    ctrl_sansMatricule_d: "Le matricule identifie le salarié sur le bulletin et à la CNPS : complétez la fiche RH.",
    ctrl_sansSalaire: "{nom} — salaire de base absent",
    ctrl_sansSalaire_d: "Indiquez le salaire de base dans la fiche RH.",
    ctrl_netNegatif: "{nom} — net négatif",
    ctrl_netNegatif_d: "Les retenues dépassent la rémunération ({montant}). Réduisez l'avance ou étalez-la.",
    ctrl_nonEnregistre: "{nom} — bulletin pas encore préparé",
    ctrl_nonEnregistre_d: "Les montants sont calculés mais pas enregistrés : préparez les bulletins.",
    ctrl_sansBanque: "{nom} — pas de banque pour le virement",
    ctrl_sansBanque_d: "Ajoutez la banque et le RIB dans la fiche RH, ou choisissez un autre moyen de paiement.",
    ctrl_sansMobile: "{nom} — pas de numéro Mobile Money",
    ctrl_sansMobile_d: "Ajoutez le téléphone dans la fiche RH, ou choisissez un autre moyen de paiement.",
    ctrl_sansCnps: "{nom} — numéro CNPS manquant",
    ctrl_sansCnps_d: "Nécessaire pour la déclaration mensuelle et la DISA.",
    ctrl_sousSmig: "{nom} — brut sous le SMIG",
    ctrl_sousSmig_d: "Brut de {montant} pour un mois complet : vérifiez le contrat ou le temps de travail.",
    ctrl_absenceInjustifiee: "{nom} — {jours} jour(s) d'absence non justifiée",
    ctrl_absenceInjustifiee_d: "Reprise de l'app Congés : retenue de {montant}.",
    ctrl_variation: "{nom} — net en variation de {pourcent} %",
    ctrl_variation_d: "Écart important avec le mois précédent : vérifiez primes, absences et retenues.",
    ctrl_entree: "{nom} — entrée le {date}",
    ctrl_entree_d: "Salaire proratisé sur {jours} jours ouvrables sur {sur}.",
    ctrl_sortie: "{nom} — sortie le {date}",
    ctrl_sortie_d: "Salaire proratisé sur {jours} jours ouvrables sur {sur}. Pensez au solde de tout compte.",
    voir: "Voir",
    corriger: "Corriger",
    ouvrirRh: "Fiche RH",

    // Variables
    titreVariables: "Éléments variables · {mois}",
    sousVariables: "Absences et frais repris automatiquement · une ligne s'enregistre quand vous la quittez",
    importer: "Importer (CSV)",
    terminer: "Terminer la saisie",
    origine: "Origine des valeurs",
    orgConges: "Congés",
    orgCongesD: "absences approuvées",
    orgFrais: "Frais",
    orgFraisD: "notes de frais approuvées, remboursées sur le bulletin",
    orgContrat: "Contrat",
    orgContratD: "éléments du dossier RH",
    orgSaisi: "Saisi",
    orgSaisiD: "modifié à la main ce mois",
    colAbsences: "Absences",
    colHeuresSup: "Heures sup.",
    colPrimes: "Primes",
    colAvance: "Avance, prêt",
    colTransport: "Transport",
    colFrais: "Frais remboursés",
    colPaiement: "Paiement",
    colNetEstime: "Net estimé",
    base: "Base {montant} · {anc}",
    ancNon: "sans ancienneté",
    ancOui: "ancienneté {taux} %",
    joursNonPayes: "{n} j non payé(s)",
    joursCongeInfo: "{n} j de congé",
    joursMaladieInfo: "{n} j maladie",
    aucune: "—",
    hsResume: "{h} h · {montant}",
    totalLigne: "{n} salarié(s) · {prets} préparé(s)",
    totPrimes: "Primes",
    totHs: "Heures sup.",
    totFrais: "Frais remboursés",
    totNet: "Net estimé",
    apercu: "{nom} · aperçu en direct",
    voirBulletin: "Bulletin →",
    baisseNet: "Net en baisse de {montant} par rapport au mois précédent.",
    hausseNet: "Net en hausse de {montant} par rapport au mois précédent.",
    majTitre: "Heures supplémentaires",
    majAide: "Majorations appliquées au taux horaire du contrat (base {h} h).",
    maj_h15: "De la 41e à la 46e heure",
    maj_h50: "Au-delà de la 46e heure",
    maj_h75: "Nuit, dimanche ou jour férié",
    maj_h100: "Nuit de dimanche ou jour férié",
    heuresDe: "Heures supplémentaires de {nom}",
    enregistrer: "Enregistrer",
    annuler: "Annuler",
    mode_virement: "Virement",
    mode_mobile: "Mobile Money",
    mode_especes: "Espèces",
    figee: "Paie validée : les éléments ne se modifient plus.",
    importAide: "Colonnes reconnues : Matricule ; Primes ; Avance ; Heures 15 ; Heures 50 ; Heures 75 ; Heures 100 ; Transport.",
    importOk: "{n} salarié(s) mis à jour depuis « {fichier} ».",
    importVide: "Aucune ligne reconnue : vérifiez la colonne Matricule.",
    depuisOrdinateur: "Depuis l'ordinateur",
    depuisCloud: "Depuis le Cloud",

    // Bulletin
    titreBulletin: "{nom} · bulletin {deMois}",
    brouillon: "Brouillon — se fige à la validation du mois",
    fige: "Figé — paie validée",
    precedent: "Salarié précédent",
    suivant: "Salarié suivant",
    telechargerPdf: "Aperçu PDF",
    marquerVerifie: "Enregistrer le bulletin",
    remettre: "Remettre le bulletin",
    envPdf: "Télécharger le bulletin",
    envPdfD: "PDF conforme, avec le logo de la fiche entreprise",
    envCourrier: "Envoyer par Courrier",
    envCourrierD: "À {email}, bulletin en pièce jointe",
    envCourrierSans: "Aucune adresse e-mail dans la fiche RH",
    envCloud: "Ranger dans le Cloud",
    envCloudD: "Dossier Paie, {fichier}",
    simTitre: "Simulateur",
    simBrutNet: "Brut → net",
    simNetBrut: "Net → brut",
    simBrut: "Brut mensuel",
    simNet: "Net voulu",
    simSituation: "Situation",
    simEnfants: "Enfants",
    simResNet: "Net à payer",
    simResBrut: "Brut nécessaire",
    simResCout: "Coût employeur",
    simResTaux: "Taux de prélèvement",
    simAide: "Pour une embauche ou une augmentation : rien n'est enregistré.",
    historique: "Bulletins précédents",
    aucunHistorique: "Premier bulletin de ce salarié.",
    situation_celibataire: "Célibataire",
    situation_marie: "Marié(e)",
    situation_veuf: "Veuf(ve)",
    netAPayer: "Net à payer",
    coutMois: "Coût total employeur ce mois : {montant}.",
    choisirSalarie: "Choisissez un salarié dans la liste.",
    elementsMois: "Éléments du mois",
    personnesCmu: "Personnes couvertes CMU",

    // Paiement et déclarations
    titrePaiement: "Paiement et déclarations · {mois}",
    sousPaiementAvant: "Validez d'abord la paie : les montants seront alors figés.",
    sousPaiement: "Paie validée le {date} · bulletins figés",
    livreDePaie: "Livre de paie (Excel)",
    envoyerTous: "Envoyer les {n} bulletins",
    envoyerTousTitre: "Envoyer {n} bulletin(s) par e-mail ?",
    envoyerTousMsg: "Chaque salarié reçoit son bulletin PDF à l'adresse de sa fiche RH. {sans} salarié(s) sans adresse seront ignorés.",
    envoyerTousOk: "{n} bulletin(s) envoyé(s), rangés aussi dans le Cloud (dossier Paie).",
    envoyerTousErr: "{n} envoi(s) impossible(s) : {raison}",
    payer: "Payer les salaires · {montant}",
    payerAide: "Chaque salarié est payé par le moyen choisi dans ses éléments du mois",
    pay_virement: "Virement bancaire",
    pay_mobile: "Mobile Money",
    pay_especes: "Espèces",
    payD_virement: "{n} salarié(s) · ordre de virement rangé dans le Cloud",
    payD_mobile: "{n} salarié(s) · liste de paiement groupé",
    payD_especes: "{n} salarié(s) · bordereau d'émargement à faire signer",
    payA_virement: "Ordre de virement",
    payA_mobile: "Exporter la liste",
    payA_especes: "Bordereau d'émargement",
    marquerPaye: "Marquer comme payée",
    marquerPayeTitre: "La paie {deMois} a-t-elle été versée ?",
    marquerPayeDetail: "Les notes de frais remboursées sur les bulletins passeront à « Remboursée » dans l'app Frais.",
    pret: "Prêt",
    paye: "Payé",
    declTitre: "Déclarations sociales et fiscales",
    declAide: "Montants calculés depuis les bulletins validés",
    echeance: "Échéance",
    decl_cnps: "CNPS — déclaration mensuelle des cotisations",
    declD_cnps: "Retraite {r} · prestations familiales {pf} · accident du travail {at}",
    decl_its: "DGI — impôt sur les traitements et salaires (ITS)",
    declD_its: "Retenue à la source, barème 2024 · état mensuel à déposer sur e-impots",
    decl_fdfp: "FDFP — apprentissage et formation continue",
    declD_fdfp: "Taxes employeur sur la masse salariale brute",
    decl_cmu: "CMU — couverture maladie universelle",
    declD_cmu: "{n} personne(s) couverte(s)",
    bordereau: "Bordereau PDF",
    marquerDeclare: "Marquer déclaré",
    declareLe: "Déclaré le {date}",
    disaTitre: "DISA {annee}",
    disaTexte: "Les cumuls de l'année se construisent mois après mois. Exportez-les pour e-DISA de la CNPS une fois décembre validé.",
    disaExport: "Exporter les cumuls",
    ecritureTitre: "Écriture de paie",
    ecritureEnvoyee: "Proposée à la Comptabilité",
    ouvrirCompta: "Ouvrir dans la Comptabilité →",
    retardCnps: "Un retard de déclaration CNPS coûte 10 % des cotisations du mois.",
    fichierRange: "« {nom} » est dans votre Cloud.",
    exporte: "Fichier enregistré",

    // Réglages
    titreReglages: "Barèmes et rubriques",
    sousReglages: "Les taux changent par décret : ils se règlent ici, pas dans le code. Vérifiez-les avec votre comptable.",
    regCnps: "CNPS",
    regRetraiteSal: "Retraite, part salariale (%)",
    regRetraiteEmp: "Retraite, part patronale (%)",
    regPf: "Prestations familiales (%)",
    regAt: "Accident du travail (%)",
    regPlafond: "Plafond retraite (F / mois)",
    regPlafondPf: "Plafond prestations et AT (F / mois)",
    regFdfp: "FDFP",
    regApprentissage: "Taxe d'apprentissage (%)",
    regFormation: "Formation continue (%)",
    regCmu: "CMU",
    regCmuMontant: "Par personne couverte (F)",
    regCmuEmployeur: "À la charge de l'employeur",
    regDivers: "Rémunération",
    regSmig: "SMIG mensuel (F)",
    regTransport: "Indemnité de transport proposée (F)",
    regHeures: "Heures mensuelles de référence",
    regJours: "Jours ouvrables de référence",
    regAnciennete: "Prime d'ancienneté",
    regAncActif: "Appliquer la prime d'ancienneté",
    regAncApres: "À partir de (années)",
    regAncInitial: "Taux initial (%)",
    regAncParAn: "Par année en plus (%)",
    regAncMax: "Plafond (%)",
    regIts: "Barème ITS (mensuel)",
    regItsJusqua: "Jusqu'à (F)",
    regItsTaux: "Taux (%)",
    regItsInfini: "au-delà",
    regRicf: "Par demi-part au-delà de la première (F)",
    regEnregistrer: "Enregistrer les barèmes",
    regDefaut: "Revenir aux valeurs par défaut",
    regEnregistre: "Barèmes enregistrés",
    regEnregistreMsg: "Ils s'appliquent aux bulletins préparés à partir de maintenant ; les paies validées ne changent pas.",
    regAdmin: "Seuls les administrateurs modifient les barèmes.",

    // Rubriques (affichage)
    rub_salaireBase: "Salaire de base",
    rub_prorata: "Entrée ou sortie en cours de mois",
    rub_anciennete: "Prime d'ancienneté",
    rub_heuresSup: "Heures supplémentaires",
    rub_primes: "Primes",
    rub_absences: "Absences non rémunérées",
    rub_brut: "Brut imposable",
    rub_cnpsRetraite: "CNPS — retraite",
    rub_cnpsPf: "CNPS — prestations familiales",
    rub_cnpsAt: "CNPS — accident du travail",
    rub_its: "Impôt sur les traitements et salaires",
    rub_cmu: "Couverture maladie universelle",
    rub_fdfp: "FDFP — apprentissage et formation",
    rub_transport: "Indemnité de transport",
    rub_frais: "Remboursement de frais",
    rub_avances: "Avance sur salaire",
    colRubrique: "Rubrique",
    colBase: "Base",
    colTaux: "Taux",
    colGain: "Gain",
    colRetenue: "Retenue",
    colPatronal: "Patronal",
    titreFeuille: "Bulletin de paie",
    ans: "ans",
  },
  en: {
    appNom: "Payroll",
    verrou: "Sign in to run payroll.",
    grpSuivre: "Overview",
    grpPreparer: "Prepare",
    grpPayer: "Pay and file",
    grpReglages: "Settings",
    navCycle: "Monthly run",
    navVariables: "Pay variables",
    navBulletins: "Payslips",
    navPaiement: "Payment and filings",
    navReglages: "Rates and items",
    moisDePaie: "Pay month",
    langue: "Language",
    langueAuto: "automatic (system)",
    actualiser: "Refresh",
    retourCycle: "Monthly run",

    titreCycle: "{mois} payroll",
    sousCycle: "Payday {date} · {n} employee(s)",
    sousCycleJ: "Payday {date} · in {j} day(s) · {n} employee(s)",
    simulateur: "Gross ↔ net calculator",
    continuerVariables: "Continue: pay variables",
    etape_variables: "Pay variables",
    etape_controles: "Checks",
    etape_validation: "Approval",
    etape_paiement: "Payment",
    etape_declarations: "Filings",
    detVariables: "{prets} / {total} payslips prepared",
    detControles: "{n} required action(s)",
    detControlesOk: "Nothing blocking",
    detValidation: "By management",
    detValide: "Approved on {date}",
    detPaiement: "Bank, Mobile Money, cash",
    detPaye: "Paid on {date}",
    detDeclarations: "CNPS, ITS, FDFP, CMU",
    detDeclare: "Everything filed",
    kpiBrut: "Gross payroll",
    kpiNet: "Net to pay",
    kpiCout: "Employer cost",
    kpiEffectif: "Headcount",
    aideBrut: "{ecart} vs previous month",
    aideBrutNeuf: "First payroll month",
    aideNet: "Transfer {v} · Mobile Money {m} · cash {e}",
    aideCout: "incl. {c} employer contributions",
    aideEffectif: "{entrees} hire(s) · {sorties} leaver(s)",
    actionsRequises: "Required actions · {n}",
    actionsAide: "Payroll can't be approved while a red item remains",
    aucuneAction: "Nothing to report: payroll can be approved.",
    salariesDuMois: "This month's employees",
    rechercher: "Search…",
    colSalarie: "Employee",
    colPoste: "Position",
    colBrut: "Gross",
    colNet: "Net pay",
    colEcart: "vs prev.",
    colStatut: "Status",
    nouveau: "new",
    st_pret: "Ready",
    st_verifier: "Check",
    st_bloque: "Blocked",
    st_entree: "Hire",
    st_sortie: "Leaver",
    echeances: "Deadlines",
    echVersement: "Salary payment",
    echVersementDet: "Prepare the transfer order the day before at the latest",
    echDeclarations: "{mois} CNPS, ITS and FDFP",
    echDeclarationsDet: "Amounts computed on approval",
    echDisa: "{annee} DISA",
    echDisaDet: "Annual salary return to the CNPS",
    echFait: "Done on {date}",
    masseSixMois: "Employer cost over 6 months",
    masseAide: "Gross + employer contributions + CMU + FDFP",
    aucunSalarie: "No employee to pay this month. Employee files come from the Human resources app.",
    preparerTout: "Prepare all payslips",
    valider: "Approve payroll",
    validerTitre: "Approve {mois} payroll?",
    validerMessage: "{n} payslip(s) will be locked: total net {net}.",
    validerDetail: "After approval, a correction requires reopening the month (administrators).",
    validerAttention: "{n} warning(s) remain open.",
    validee: "{mois} payroll approved",
    valideeMsg: "{n} payslip(s) locked, ready to be paid.",
    rouvrir: "Reopen the month",
    rouvrirTitre: "Reopen {mois} payroll?",
    rouvrirDetail: "Payslips become editable again. Those already handed out will have to be sent again.",
    moisValide: "Payroll approved on {date}{par}: payslips locked.",
    moisPaye: "Payroll paid on {date}: payslips locked.",

    ctrl_sansMatricule: "{nom} — no employee number",
    ctrl_sansMatricule_d: "The employee number identifies the person on the payslip and at the CNPS: complete the HR file.",
    ctrl_sansSalaire: "{nom} — no base salary",
    ctrl_sansSalaire_d: "Enter the base salary in the HR file.",
    ctrl_netNegatif: "{nom} — negative net pay",
    ctrl_netNegatif_d: "Deductions exceed pay ({montant}). Reduce or spread the advance.",
    ctrl_nonEnregistre: "{nom} — payslip not prepared yet",
    ctrl_nonEnregistre_d: "Amounts are computed but not saved: prepare the payslips.",
    ctrl_sansBanque: "{nom} — no bank for the transfer",
    ctrl_sansBanque_d: "Add the bank details to the HR file, or choose another payment method.",
    ctrl_sansMobile: "{nom} — no Mobile Money number",
    ctrl_sansMobile_d: "Add the phone number to the HR file, or choose another payment method.",
    ctrl_sansCnps: "{nom} — CNPS number missing",
    ctrl_sansCnps_d: "Required for the monthly return and the DISA.",
    ctrl_sousSmig: "{nom} — gross below the minimum wage",
    ctrl_sousSmig_d: "Gross of {montant} for a full month: check the contract or working time.",
    ctrl_absenceInjustifiee: "{nom} — {jours} day(s) of unexcused absence",
    ctrl_absenceInjustifiee_d: "From the Leave app: {montant} deducted.",
    ctrl_variation: "{nom} — net pay changed by {pourcent}%",
    ctrl_variation_d: "Large difference with last month: check bonuses, absences and deductions.",
    ctrl_entree: "{nom} — joined on {date}",
    ctrl_entree_d: "Salary prorated over {jours} of {sur} working days.",
    ctrl_sortie: "{nom} — leaves on {date}",
    ctrl_sortie_d: "Salary prorated over {jours} of {sur} working days. Remember the final settlement.",
    voir: "View",
    corriger: "Fix",
    ouvrirRh: "HR file",

    titreVariables: "Pay variables · {mois}",
    sousVariables: "Absences and expenses imported automatically · a row is saved when you leave it",
    importer: "Import (CSV)",
    terminer: "Finish",
    origine: "Where values come from",
    orgConges: "Leave",
    orgCongesD: "approved absences",
    orgFrais: "Expenses",
    orgFraisD: "approved expense claims, reimbursed on the payslip",
    orgContrat: "Contract",
    orgContratD: "from the HR file",
    orgSaisi: "Entered",
    orgSaisiD: "changed by hand this month",
    colAbsences: "Absences",
    colHeuresSup: "Overtime",
    colPrimes: "Bonuses",
    colAvance: "Advance, loan",
    colTransport: "Transport",
    colFrais: "Expenses",
    colPaiement: "Payment",
    colNetEstime: "Est. net",
    base: "Base {montant} · {anc}",
    ancNon: "no seniority",
    ancOui: "seniority {taux}%",
    joursNonPayes: "{n} unpaid day(s)",
    joursCongeInfo: "{n} day(s) leave",
    joursMaladieInfo: "{n} sick day(s)",
    aucune: "—",
    hsResume: "{h} h · {montant}",
    totalLigne: "{n} employee(s) · {prets} prepared",
    totPrimes: "Bonuses",
    totHs: "Overtime",
    totFrais: "Expenses",
    totNet: "Est. net",
    apercu: "{nom} · live preview",
    voirBulletin: "Payslip →",
    baisseNet: "Net pay down {montant} vs last month.",
    hausseNet: "Net pay up {montant} vs last month.",
    majTitre: "Overtime",
    majAide: "Premiums applied to the contract hourly rate (base {h} h).",
    maj_h15: "41st to 46th hour",
    maj_h50: "Beyond the 46th hour",
    maj_h75: "Night, Sunday or public holiday",
    maj_h100: "Sunday or holiday night",
    heuresDe: "Overtime for {nom}",
    enregistrer: "Save",
    annuler: "Cancel",
    mode_virement: "Transfer",
    mode_mobile: "Mobile Money",
    mode_especes: "Cash",
    figee: "Payroll approved: variables can no longer change.",
    importAide: "Recognised columns: Matricule; Primes; Avance; Heures 15; Heures 50; Heures 75; Heures 100; Transport.",
    importOk: "{n} employee(s) updated from “{fichier}”.",
    importVide: "No row recognised: check the Matricule column.",
    depuisOrdinateur: "From this computer",
    depuisCloud: "From the Cloud",

    titreBulletin: "{nom} · {mois} payslip",
    brouillon: "Draft — locked when the month is approved",
    fige: "Locked — payroll approved",
    precedent: "Previous employee",
    suivant: "Next employee",
    telechargerPdf: "PDF preview",
    marquerVerifie: "Save payslip",
    remettre: "Hand out the payslip",
    envPdf: "Download the payslip",
    envPdfD: "Compliant PDF, with the company logo (in French, the legal language)",
    envCourrier: "Send with Mail",
    envCourrierD: "To {email}, payslip attached",
    envCourrierSans: "No email address in the HR file",
    envCloud: "Save to the Cloud",
    envCloudD: "Payroll folder, {fichier}",
    simTitre: "Calculator",
    simBrutNet: "Gross → net",
    simNetBrut: "Net → gross",
    simBrut: "Monthly gross",
    simNet: "Target net",
    simSituation: "Status",
    simEnfants: "Children",
    simResNet: "Net pay",
    simResBrut: "Gross needed",
    simResCout: "Employer cost",
    simResTaux: "Deduction rate",
    simAide: "For a hire or a raise: nothing is saved.",
    historique: "Previous payslips",
    aucunHistorique: "First payslip for this employee.",
    situation_celibataire: "Single",
    situation_marie: "Married",
    situation_veuf: "Widowed",
    netAPayer: "Net pay",
    coutMois: "Total employer cost this month: {montant}.",
    choisirSalarie: "Choose an employee from the list.",
    elementsMois: "This month's items",
    personnesCmu: "People covered by CMU",

    titrePaiement: "Payment and filings · {mois}",
    sousPaiementAvant: "Approve payroll first: amounts will then be locked.",
    sousPaiement: "Payroll approved on {date} · payslips locked",
    livreDePaie: "Payroll ledger (Excel)",
    envoyerTous: "Send the {n} payslips",
    envoyerTousTitre: "Email {n} payslip(s)?",
    envoyerTousMsg: "Each employee receives their PDF payslip at the address in their HR file. {sans} employee(s) without an address will be skipped.",
    envoyerTousOk: "{n} payslip(s) sent, also saved to the Cloud (Paie folder).",
    envoyerTousErr: "{n} could not be sent: {raison}",
    payer: "Pay salaries · {montant}",
    payerAide: "Each employee is paid with the method chosen in their monthly items",
    pay_virement: "Bank transfer",
    pay_mobile: "Mobile Money",
    pay_especes: "Cash",
    payD_virement: "{n} employee(s) · transfer order saved to the Cloud",
    payD_mobile: "{n} employee(s) · bulk payment list",
    payD_especes: "{n} employee(s) · signature sheet",
    payA_virement: "Transfer order",
    payA_mobile: "Export the list",
    payA_especes: "Signature sheet",
    marquerPaye: "Mark as paid",
    marquerPayeTitre: "Has {mois} payroll been paid?",
    marquerPayeDetail: "Expense claims reimbursed on payslips will be set to “Reimbursed” in the Expenses app.",
    pret: "Ready",
    paye: "Paid",
    declTitre: "Social and tax filings",
    declAide: "Amounts computed from approved payslips",
    echeance: "Due",
    decl_cnps: "CNPS — monthly contributions return",
    declD_cnps: "Pension {r} · family benefits {pf} · work accident {at}",
    decl_its: "DGI — wage tax (ITS)",
    declD_its: "Withheld at source, 2024 scale · monthly return on e-impots",
    decl_fdfp: "FDFP — apprenticeship and training levies",
    declD_fdfp: "Employer levies on gross payroll",
    decl_cmu: "CMU — universal health coverage",
    declD_cmu: "{n} person(s) covered",
    bordereau: "PDF return",
    marquerDeclare: "Mark as filed",
    declareLe: "Filed on {date}",
    disaTitre: "{annee} DISA",
    disaTexte: "Year-to-date totals build up month after month. Export them for the CNPS e-DISA once December is approved.",
    disaExport: "Export totals",
    ecritureTitre: "Payroll journal entry",
    ecritureEnvoyee: "Offered to Accounting",
    ouvrirCompta: "Open in Accounting →",
    retardCnps: "A late CNPS return costs 10% of the month's contributions.",
    fichierRange: "“{nom}” is in your Cloud.",
    exporte: "File saved",

    titreReglages: "Rates and items",
    sousReglages: "Rates change by decree: they are set here, not in the code. Check them with your accountant.",
    regCnps: "CNPS",
    regRetraiteSal: "Pension, employee share (%)",
    regRetraiteEmp: "Pension, employer share (%)",
    regPf: "Family benefits (%)",
    regAt: "Work accident (%)",
    regPlafond: "Pension ceiling (XOF / month)",
    regPlafondPf: "Benefits and accident ceiling (XOF / month)",
    regFdfp: "FDFP",
    regApprentissage: "Apprenticeship levy (%)",
    regFormation: "Continuing training (%)",
    regCmu: "CMU",
    regCmuMontant: "Per person covered (XOF)",
    regCmuEmployeur: "Paid by the employer",
    regDivers: "Pay",
    regSmig: "Monthly minimum wage (XOF)",
    regTransport: "Suggested transport allowance (XOF)",
    regHeures: "Reference monthly hours",
    regJours: "Reference working days",
    regAnciennete: "Seniority bonus",
    regAncActif: "Apply the seniority bonus",
    regAncApres: "From (years)",
    regAncInitial: "Initial rate (%)",
    regAncParAn: "Per extra year (%)",
    regAncMax: "Cap (%)",
    regIts: "ITS scale (monthly)",
    regItsJusqua: "Up to (XOF)",
    regItsTaux: "Rate (%)",
    regItsInfini: "above",
    regRicf: "Per half-share beyond the first (XOF)",
    regEnregistrer: "Save rates",
    regDefaut: "Reset to defaults",
    regEnregistre: "Rates saved",
    regEnregistreMsg: "They apply to payslips prepared from now on; approved payrolls do not change.",
    regAdmin: "Only administrators can change rates.",

    rub_salaireBase: "Base salary",
    rub_prorata: "Hire or exit during the month",
    rub_anciennete: "Seniority bonus",
    rub_heuresSup: "Overtime",
    rub_primes: "Bonuses",
    rub_absences: "Unpaid absences",
    rub_brut: "Taxable gross",
    rub_cnpsRetraite: "CNPS — pension",
    rub_cnpsPf: "CNPS — family benefits",
    rub_cnpsAt: "CNPS — work accident",
    rub_its: "Wage tax (ITS)",
    rub_cmu: "Universal health coverage",
    rub_fdfp: "FDFP — apprenticeship and training",
    rub_transport: "Transport allowance",
    rub_frais: "Expense reimbursement",
    rub_avances: "Salary advance",
    colRubrique: "Item",
    colBase: "Base",
    colTaux: "Rate",
    colGain: "Earning",
    colRetenue: "Deduction",
    colPatronal: "Employer",
    titreFeuille: "Payslip",
    ans: "yrs",
  },
};

/// Un montant en francs CFA, écrit à la manière de la langue : « 3 742 500 F »
/// en français, « XOF 3,742,500 » en anglais. La paie reste en francs CFA
/// quelle que soit la devise d'affichage : un bulletin ne se convertit pas.
export const formateur = (langue) => (n) => {
  const v = Math.round(Number(n) || 0);
  return langue === "en" ? `XOF ${v.toLocaleString("en-US")}` : `${v.toLocaleString("fr-FR")} F`;
};

/// « d'octobre », « de mars » : l'élision devant une voyelle ou un h muet.
export const deMois = (nom) => (/^[aeiouyhàâéè]/i.test(nom) ? `d'${nom}` : `de ${nom}`);

export const nombreDe = (langue) => (n) =>
  Math.round(Number(n) || 0).toLocaleString(langue === "en" ? "en-US" : "fr-FR");

export const nomDuMois = (mois, langue, { annee = true, court = false } = {}) =>
  new Date(`${mois}-15T12:00:00Z`).toLocaleDateString(langue === "en" ? "en-US" : "fr-FR", {
    month: court ? "short" : "long",
    ...(annee ? { year: "numeric" } : {}),
  });

export const dateDe = (iso, langue) =>
  iso
    ? new Date(`${iso}T12:00:00Z`).toLocaleDateString(langue === "en" ? "en-US" : "fr-FR", {
        day: "numeric",
        month: "short",
        year: "numeric",
      })
    : "";
