// Campagnes — les textes, en français et en anglais.
//
// La langue suit celle du système (réglage « Langue et région »,
// automatique par défaut). La langue d'un **message** envoyé, elle, se
// choisit dans l'éditeur : on écrit à ses clients dans leur langue, pas
// dans celle de son écran.

const FR = {
  appNom: "Campagnes",
  verrou: "Connectez-vous pour lancer des campagnes.",
  langueAuto: "Langue : automatique",
  votreEntreprise: "Votre entreprise",
  joignablesN: "{n} contacts joignables",
  erreur: "Erreur",

  grpEnvoyer: "Envoyer",
  grpAudience: "Audience",
  navAccueil: "Accueil",
  navCampagnes: "Campagnes",
  navAutomatisations: "Automatisations",
  navModeles: "Modèles",
  navContacts: "Contacts et listes",
  navFormulaire: "Formulaire d'inscription",

  // Communs
  annuler: "Annuler",
  enregistrer: "Enregistrer",
  enregistre: "Enregistré",
  supprimer: "Supprimer",
  modifier: "Modifier",
  dupliquer: "Dupliquer",
  exporter: "Exporter",
  fermer: "Fermer",
  continuer: "Continuer",
  retour: "Retour",
  voir: "Voir",
  ajouter: "Ajouter",
  envoyer: "Envoyer",
  utiliser: "Utiliser",
  copier: "Copier",
  copie: "Copié",
  gerer: "Gérer",
  toutes: "Toutes",
  reduire: "Réduire",
  toutVoir: "Tout voir",
  toutCocher: "Tout cocher",
  toutDecocher: "Tout décocher",
  filtrer: "Filtrer",
  vue: "Vue",
  maintenant: "maintenant",
  apercu: "Aperçu",
  objetVide: "(objet du message)",
  sansNom: "Sans nom",
  aucunResultat: "Aucun résultat pour ces filtres.",
  nom: "Nom",
  email: "E-mail",
  telephone: "Téléphone",
  ville: "Ville",
  entreprise: "Entreprise",
  contact: "Contact",
  statut: "Statut",
  version: "Version",
  erreurColonne: "Erreur",
  nJours: "{n} jours",
  nHeures: "{n} h",
  nMinutes: "environ {n} min",
  nDestinataires: "{n} destinataires",
  nContacts: "{n} contacts",
  nEnvoyes: "{n} envoyés",
  nFactures: "{n} factures",
  afficherPlus: "Afficher plus ({n} restants)",
  affichesSur: "{a} sur {b} affichés",
  conseille: "conseillé",
  actif: "Actif",
  active: "Active",
  enPause: "En pause",
  enCours: "En cours",
  envoyes: "Envoyés",
  sortis: "Sortis",
  ouverture: "Ouverture",
  clics: "Clics",
  caAttribue: "CA attribué",
  campagne: "Campagne",
  destinataires: "Destinataires",
  destinatairesMin: "destinataires",
  message: "Message",
  objet: "Objet",
  reglages: "Réglages",
  ficheCRM: "Fiche CRM →",
  rebond: "Rebond",
  rebonds: "Rebonds",
  desinscrit: "Désinscrit",
  desinscrits: "Désinscrits",
  desinscriptions: "Désinscriptions",
  aConfirmer: "Inscription à confirmer",
  nonConfirme: "À confirmer",
  sansEmail: "Sans e-mail valide",
  doublons: "Adresses en double",
  auRepos: "Au repos",
  ecartesMain: "Écartés à la main",
  joignables: "Joignables",
  ouvert: "Ouvert",
  clique: "A cliqué",
  echec: "Échec",
  sorti: "Sorti",
  ouvertLe: "Ouvert le",
  cliqueLe: "Cliqué le",
  erreurCsv: "Erreur",
  etiquette: "Étiquette",
  etiquettes: "Étiquettes",
  engagement: "Engagement",
  consentement: "Consentement",
  dernierAchat: "Dernier achat",

  statut_brouillon: "Brouillon",
  statut_programmee: "Programmée",
  statut_envoi: "Envoi en cours",
  statut_pause: "En pause",
  statut_terminee: "Terminée",

  crm_tous: "Tous",
  crm_actif: "Clients actifs",
  crm_prospect: "Prospects",
  crm_inactif: "Inactifs",

  origine_formulaire: "Formulaire",
  origine_import: "Import",
  origine_crm: "CRM",

  source_crm: "CRM",
  source_facturation: "Facturation",
  source_stock: "Stock",

  // Accueil
  bonjour: "Bonjour {nom}",
  sousAccueil: "{c} campagne(s) programmée(s) ou en cours, {a} automatisation(s) au travail",
  nouvelleCampagne: "Nouvelle campagne",
  nouvelleAuto: "Nouvelle automatisation",
  kJoignables: "Contacts joignables",
  kJoignablesD: "+{n} nouveaux en 30 jours",
  kEnvoyes: "Envoyés sur 30 jours",
  kEnvoyesD: "{n} campagne(s)",
  kOuverture: "Taux d'ouverture moyen",
  kOuvertureD: "campagnes terminées",
  kClicD: "{p} de clics en moyenne",
  kCA: "CA attribué (30 j)",
  kCAD: "factures émises dans les 7 j suivant un clic",
  aFaire: "À faire",
  rienAFaire: "Rien d'urgent : tout est à jour.",
  tAB: "Test A/B tranché : la version {v} gagne ({a} % contre {b} %)",
  tRebonds: "{n} adresse(s) en rebond définitif",
  tRebondsD: "Suspendues automatiquement : corrigez-les dans le CRM puis réactivez-les",
  tProgrammees: "{n} campagne(s) programmée(s)",
  tRelance: "{n} personnes n'ont pas ouvert",
  tAConfirmer: "{n} inscription(s) en attente de confirmation",
  tAConfirmerD: "Elles recevront vos campagnes dès qu'elles auront cliqué le lien de confirmation",
  tAuto: "Mettez votre emailing en pilote automatique",
  tAutoD: "Bienvenue, devis non signé, merci après achat… prêtes à activer",
  tBrouillons: "{n} brouillon(s) à terminer",
  corriger: "Corriger",
  relancer: "Relancer",
  decouvrir: "Découvrir",
  reprendre: "Reprendre",
  campagnesRecentes: "Campagnes récentes",
  aucuneCampagne: "Aucune campagne pour l'instant",
  aucuneCampagneD: "Écrivez à vos clients du CRM, suivez qui ouvre, qui clique et ce que cela vend.",
  premiereCampagne: "Créer ma première campagne",
  testAB: "Test A/B",
  aucuneAutoD: "Aucune automatisation : activez une recette en deux clics.",
  santeListe: "Santé de la liste",
  sansEmailOuAConfirmer: "Sans e-mail ou à confirmer",
  gererContacts: "Gérer les contacts",

  // Liste des campagnes
  sousCampagnes: "{n} campagne(s)",
  rechercherCampagne: "Rechercher une campagne",
  onglet_toutes: "Toutes",
  onglet_brouillon: "Brouillons",
  onglet_programmee: "Programmées",
  onglet_envoi: "En cours",
  onglet_terminee: "Terminées",

  // Éditeur — en-tête et étapes
  nomInterne: "Nom interne",
  nomInterneExemple: "Offre de rentrée, fermeture annuelle…",
  etapes: "Étapes",
  etape_audience: "Audience",
  etape_contenu: "Contenu",
  etape_envoi: "Envoi",
  continuerContenu: "Continuer : le contenu",
  continuerEnvoi: "Continuer : l'envoi",
  nommerDabord: "Donnez d'abord un nom interne",
  partirModele: "Partir d'un modèle",
  enregistrerModele: "Enregistrer comme modèle",
  nomModele: "Nom du modèle",
  modeleEnregistre: "Modèle enregistré",
  modeleCourrier: "Modèle Courrier",
  aucunModele: "Aucun modèle enregistré.",
  remplacerTitre: "Remplacer le contenu ?",
  remplacerMessage: "Les blocs actuels seront remplacés par ceux du modèle.",
  remplacer: "Remplacer",
  envoyerTest: "Envoyer un test",
  renvoyerTest: "Renvoyer le test",
  testAide: "Le test part tel que vos clients le recevront, aux membres de l'équipe seulement (5 au plus).",
  testEnvoye: "Test envoyé",
  testImpossible: "Test impossible",
  testPartiel: "Test partiellement envoyé",
  testPartielMessage: "{n} adresse(s) écartée(s) : le test ne part qu'aux membres de l'espace.",
  quitterTitre: "Quitter sans enregistrer ?",
  quitterMessage: "Les modifications de cette campagne seront perdues.",
  quitter: "Quitter",
  bandeauRelance: "Relance de « {nom} » : seuls ceux qui n'ont pas ouvert la recevront. Changez l'objet — c'est lui qui n'a pas convaincu.",
  seulAdmin: "Seul un administrateur peut enregistrer et lancer une campagne.",
  brouillonEnregistre: "Brouillon enregistré",
  enregistrementImpossible: "Enregistrement impossible",
  creeLe: "Créée le {date}",

  // Audience
  aQui: "À qui écrivez-vous ?",
  aQuiAide: "Les contacts viennent du CRM. Chaque critère réduit l'audience.",
  listeFermee: "Liste fermée : {n} contacts choisis à la création de la relance.",
  statutCRM: "Statut CRM",
  toutesEtiquettes: "Toutes les étiquettes",
  ajouterEtiquette: "Ajouter une étiquette",
  villes: "Villes",
  toutesVilles: "Toutes les villes",
  ajouterVille: "Ajouter une ville",
  secteurs: "Secteurs",
  tousSecteurs: "Tous les secteurs",
  ajouterSecteur: "Ajouter un secteur",
  activite: "Activité",
  aRecuFacture: "A reçu une facture ces",
  periodeAchat: "Période d'achat",
  mois_1: "30 derniers jours",
  mois_3: "3 derniers mois",
  mois_6: "6 derniers mois",
  mois_12: "12 derniers mois",
  pression: "Pression",
  ecarterRecents: "Écarter ceux qui ont reçu une campagne il y a moins de",
  delaiRepos: "Délai de repos",
  destinatairesAide: "Décochez un contact pour l'écarter de cette campagne seulement.",
  rechercherContact: "Nom, e-mail, ville…",
  pasEmail: "Pas d'e-mail valide",
  enRebond: "En rebond",
  auReposLigne: "Au repos (campagne récente)",
  factureLe: "Facture le {date}",
  personne: "Personne ne correspond : élargissez les critères, ou complétez les e-mails dans le CRM.",
  audienceRetenue: "Audience retenue",
  correspondent: "Correspondent aux critères",
  dureeEnvoi: "Envoi estimé : environ {duree} min, par petits lots — pour rester hors des spams.",
  avantLancer: "Avant de lancer",
  lancer_nom: "Un nom interne",
  lancer_audience: "Une audience",
  lancer_sujet: "Un objet",
  lancer_texte: "Un message",
  lancer_cta: "Des boutons avec un lien valide",
  lancer_ab: "Deux objets différents pour le test A/B",
  lancer_test: "Un test reçu dans votre boîte",

  // Éditeur de blocs
  lienACompleter: "Lien à compléter",
  vide_titre: "Titre vide — écrivez-le à droite",
  vide_texte: "Texte vide — écrivez-le à droite",
  vide_image: "Choisissez une image : Cloud, ordinateur ou adresse en ligne",
  vide_bouton: "Bouton sans texte — complétez-le à droite",
  vide_produits: "Choisissez jusqu'à 6 articles du Stock",
  vide_colonnes: "Colonnes vides",
  vide_promo: "Saisissez un code promo",
  vide_separateur: "Séparateur",
  vide_reseaux: "Ajoutez vos liens : site, WhatsApp, Facebook…",
  vide_signature: "Signature vide",
  blocs: "Blocs",
  paletteAide: "Glissez un bloc dans le message, ou cliquez pour l'ajouter sous la sélection.",
  bloc_titre: "Titre",
  bloc_texte: "Texte",
  bloc_image: "Image",
  bloc_bouton: "Bouton",
  bloc_produits: "Produits",
  bloc_colonnes: "2 colonnes",
  bloc_promo: "Code promo",
  bloc_separateur: "Séparateur",
  bloc_reseaux: "Réseaux",
  bloc_signature: "Signature",
  blocAide_titre: "Grand titre",
  blocAide_texte: "Gras, liens, listes",
  blocAide_image: "Depuis le Cloud",
  blocAide_bouton: "Lien suivi",
  blocAide_produits: "Du Stock, prix à jour",
  blocAide_colonnes: "Deux textes côte à côte",
  blocAide_promo: "Encadré à copier",
  blocAide_separateur: "Ligne ou espace",
  blocAide_reseaux: "WhatsApp, Facebook…",
  blocAide_signature: "Le mot de la fin",
  planTravail: "Plan de travail",
  apercuReel: "Aperçu réel",
  appareil: "Appareil",
  ordinateur: "Ordinateur",
  mobile: "Mobile",
  enTeteAuto: "En-tête : logo et nom de l'entreprise",
  piedAuto: "Pied : mentions légales et lien de désinscription, ajoutés automatiquement",
  feuilleVide: "Glissez ici un premier bloc.",
  monter: "Monter",
  descendre: "Descendre",
  versionA: "Version A",
  versionB: "Version B",
  nCaracteres: "{n} caractères",
  objetExemple: "{{prenom}}, du nouveau chez {{entreprise}}",
  objetBExemple: "Une autre façon de le dire",
  partTest: "Part testée",
  delaiDecision: "Décision après",
  abExplication: "{part} % de l'audience reçoit A ou B (moitié chacun). Après {heures} h, la version au meilleur taux d'ouverture part aux autres.",
  texteApercu: "Texte d'aperçu",
  texteApercuExemple: "La ligne grise qui suit l'objet dans la boîte de réception",
  inserer: "Insérer :",
  var_client: "La société, ou le nom du contact",
  var_contact: "La personne, quand la fiche a une société",
  var_prenom: "Le prénom de la personne",
  var_ville: "La ville de la fiche",
  var_entreprise: "Le nom de votre entreprise",
  var_numero: "Le numéro du devis ou de la facture",
  var_annees: "Le nombre d'années de relation",
  blocChoisi: "Bloc sélectionné · {type}",
  aucunBloc: "Aucun bloc sélectionné",
  aucunBlocAide: "Cliquez un bloc du message pour le régler.",
  couleur: "Couleur",
  couleurLibre: "Couleur personnalisée",
  langueMessage: "Langue du message (pied, désinscription)",
  verifications: "Vérifications",
  verif_contenu: "Un titre ou un texte",
  verif_contenu_ko: "Ajoutez un titre ou un texte",
  verif_boutons: "Boutons : texte et lien valides",
  verif_boutons_ko: "Un bouton n'a pas de texte ou de lien valide",
  verif_images: "Images avec texte alternatif",
  verif_images_ko: "Une image n'a pas de texte alternatif",
  verif_poids: "Poids du message : {ko} Ko",
  verif_poids_ko: "Message lourd ({ko} Ko) : Gmail le coupera",
  verif_desabo: "Lien de désinscription présent",
  texte: "Texte",
  taille: "Taille",
  grand: "Grand",
  moyen: "Moyen",
  alignement: "Alignement",
  gauche: "Gauche",
  centre: "Centré",
  texteAide: "**gras**, [texte du lien](https://…), lignes « - » pour une liste",
  colonneGauche: "Colonne de gauche",
  colonneDroite: "Colonne de droite",
  texteBouton: "Texte du bouton",
  lien: "Lien",
  lienSuivi: "Chaque clic est compté, lien par lien.",
  lienInvalide: "Adresse invalide : elle doit commencer par https://",
  codePromo: "Code",
  style: "Style",
  ligne: "Ligne",
  espace: "Espace",
  reseau_site: "Site web",
  reseau_whatsapp: "WhatsApp (numéro)",
  reseau_facebook: "Facebook",
  reseau_instagram: "Instagram",
  reseau_linkedin: "LinkedIn",
  choisirImage: "Choisir une image",
  depuisCloud: "Depuis le Cloud",
  depuisOrdinateur: "Depuis l'ordinateur",
  imageCloud: "Image du Cloud : servie aux destinataires par une adresse signée.",
  ouAdresseImage: "Ou adresse d'une image en ligne",
  texteAlternatif: "Texte alternatif",
  texteAlternatifAide: "Lu quand les images sont bloquées — et par les lecteurs d'écran.",
  lienImage: "Lien au clic sur l'image (facultatif)",
  afficherPrix: "Afficher les prix",
  lienProduit: "Lien vers le produit (facultatif)",
  chercherArticle: "Chercher un article du Stock",
  produitsAide: "Jusqu'à 6 produits. Nom et prix repris du Stock.",
  produitsSansStock: "Installez l'app Stock et créez des articles pour les présenter ici.",

  // Envoi
  quand: "Quand ?",
  maintenantEnvoi: "Maintenant",
  departMinute: "Départ dans la minute",
  programmer: "Programmer",
  quandLisent: "À l'heure où vos clients lisent",
  creneau_demain8: "Demain 8:00",
  creneau_lundi9: "Lundi 9:00",
  creneau_mardi830: "Mardi 8:30",
  dateHeure: "Date et heure d'envoi",
  abEnvoi: "Test A/B : {part} % de l'audience d'abord, puis la meilleure version aux autres après {heures} h.",
  recapitulatif: "Récapitulatif",
  liensSuivis: "Liens suivis",
  dureeEstimee: "Durée d'envoi",
  annulableDepart: "Annulable jusqu'au départ.",
  ilManque: "Il manque : {liste}.",
  programmerCampagne: "Programmer la campagne",
  lancerEnvoi: "Lancer l'envoi",
  programmerTitre: "Programmer la campagne ?",
  lancerTitre: "Lancer la campagne ?",
  lancerMessage: "« {nom} » partira vers {n} destinataire(s).",
  lancerDepart: "Départ {quand}, par petits lots. Annulable jusqu'au départ.",
  lancerMaintenant: "Départ dans la minute, par petits lots — pour rester hors des spams.",
  lancerAB: "Test A/B sur {part} % de l'audience, décision après {heures} h.",
  lancer: "Lancer l'envoi",
  lancementImpossible: "Lancement impossible",
  campagneProgrammee: "Campagne programmée",
  campagneLancee: "Campagne lancée",

  // Rapport
  campagneIntrouvable: "Cette campagne n'existe plus.",
  departPrevu: "Départ prévu {quand}",
  envoiEnCours: "Envoi en cours : {a} sur {b} ({p} %)",
  envoyeeLe: "Envoyée {quand} {fin}",
  annulerProg: "Annuler la programmation",
  annulerProgTitre: "Annuler la programmation ?",
  annulerProgMessage: "« {nom} » redevient un brouillon : rien ne partira.",
  mettrePause: "Mettre en pause",
  reprendreEnvoi: "Reprendre l'envoi",
  relancerNonOuvreurs: "Relancer les {n} non-ouvreurs",
  progression: "Progression de l'envoi",
  versionN: "Version {v} · {n} envoyés",
  gagnant: "Gagnant",
  abEnCours: "Test en cours : la meilleure version partira aux autres {heures} h après le dernier envoi du test.",
  delivres: "Délivrés",
  pctEnvoyes: "{p} % des destinataires",
  ouverturesRobots: "ouvertures instantanées (robots) écartées",
  pctOuvreurs: "{p} % des ouvreurs",
  carteClics: "Carte des clics",
  carteClicsAide: "Part des cliqueurs sur les liens de chaque bloc",
  liens: "Liens",
  aucunLien: "Aucun lien dans ce message.",
  ventesAttribuees: "Ventes attribuées · {montant}",
  ventesAide: "Factures émises dans les 7 jours suivant un clic du même client",
  aucuneVente: "Aucune facture émise après un clic pour l'instant.",
  nJoursApres: "{n} j après le clic",
  leJourMeme: "le jour même",
  aTraiter: "À traiter",
  rebondsDefinitifs: "Rebonds définitifs",
  rebondsDefinitifsD: "Adresse inexistante : contact suspendu, signalé dans sa fiche CRM.",
  rebondsTemporaires: "Rebonds temporaires",
  rebondsTemporairesD: "Boîte pleine ou serveur occupé : nouvel essai automatique dans 6 h.",
  autresEchecs: "Autres échecs",
  reessayer: "Réessayer",
  desinscriptionsD: "Marquées dans le CRM : plus aucune campagne ne leur sera envoyée.",
  nouvelEssai: "Nouvel essai programmé",
  nouvelEssaiMessage: "Les échecs repartent au prochain passage.",
  ouverturesHeure: "Ouvertures, heure par heure",
  pic: "Pic à {h} h : {n} ouverture(s)",
  ouverturesApres: "Les ouvertures s'afficheront ici après le départ.",
  aucuneOuverture: "Aucune ouverture enregistrée pour l'instant.",
  filtre_tous: "Tous",
  filtre_ouverts: "Ouverts",
  filtre_cliques: "Ont cliqué",
  filtre_nonOuverts: "Non ouverts",
  filtre_echecs: "Échecs",
  filtre_desinscrits: "Désinscrits",
  reessaiPrevu: "Nouvel essai prévu",
  enAttente: "En attente",
  attendGagnant: "Attend la version gagnante",
  ouvertA: "Ouvert à {h}",
  cliqueA: "Cliqué à {h}",
  delivreNonOuvert: "Délivré — pas encore ouvert",
  personneCategorie: "Personne dans cette catégorie.",
  arreterTitre: "Arrêter et supprimer ?",
  arreterMessage: "« {nom} » est en cours d'envoi : les messages restants ne partiront pas.",
  supprimerCampagneTitre: "Supprimer cette campagne ?",
  supprimerCampagneMessage: "« {nom} » et ses résultats seront retirés.",

  // Automatisations
  sousAutos: "{n} active(s)",
  vosAutos: "Vos automatisations",
  automatisation: "Automatisation",
  recettes: "Recettes prêtes",
  recettesAide: "Chacune écoute une autre app de CompanyOS. Choisissez, relisez le message, activez.",
  relancesFactures: "Les rappels de factures impayées vivent dans l'app Courrier (relances automatiques) : ils ne sont pas dupliqués ici.",
  dejaN: "{n} déjà",
  recette_bienvenue: "Bienvenue",
  recette_devis: "Relance devis non signé",
  recette_merci: "Merci après achat",
  recette_livraison: "Avis après livraison",
  recette_endormi: "Client endormi",
  recette_anniversaire: "Anniversaire de relation",
  recetteD_bienvenue: "Nouveau contact au CRM ou par le formulaire",
  recetteD_devis: "Devis envoyé, toujours pas accepté",
  recetteD_merci: "Facture émise",
  recetteD_livraison: "Livraison constatée dans le Stock",
  recetteD_endormi: "Aucun achat depuis 90 jours",
  recetteD_anniversaire: "Un an de plus depuis l'entrée au CRM",
  autoIntrouvable: "Cette automatisation n'existe plus.",
  activeDepuis: "Active depuis le {date}",
  inactive: "Inactive — rien ne part",
  scenario: "Scénario",
  personnes: "Personnes",
  activer: "Activer",
  activerTitre: "Activer l'automatisation ?",
  activerMessage: "« {nom} » écrira désormais aux clients concernés, automatiquement.",
  activerDetail: "Seuls les événements à partir de maintenant comptent : personne n'est rattrapé dans le passé.",
  etapeScenario_declencheur: "Déclencheur",
  etapeScenario_attendre: "Attendre",
  etapeScenario_condition: "Condition",
  etapeScenario_email: "E-mail",
  decl_bienvenue: "Un contact entre au CRM",
  decl_devis: "Un devis passe à « Envoyé »",
  decl_merci: "Une facture est émise",
  decl_livraison: "Une facture est livrée (Stock)",
  decl_endormi: "90 jours sans achat",
  decl_anniversaire: "Date anniversaire d'entrée au CRM",
  cond_devis: "Le devis est-il toujours en attente ?",
  cond_endormi: "Toujours pas de nouvel achat ?",
  condSortie: "Sinon : sortie du scénario, pas d'e-mail",
  condIgnoree: "Condition désactivée : l'e-mail part quoi qu'il arrive",
  immediatement: "Immédiatement",
  puisCreneau: "Puis le prochain créneau ouvré (lun.–ven., 8 h–18 h)",
  sansCreneau: "À toute heure",
  emailDetail: "Le message de l'onglet « Message »",
  nEntres: "{n} entrés",
  nSortis: "{n} sortis",
  pctOuverts: "{p} ouverts",
  nomAuto: "Nom",
  delaiAvantEnvoi: "Délai avant l'envoi",
  regleOuvres: "Envoyer seulement en jours ouvrés, 8 h – 18 h",
  regleSortie_devis: "Se taire si le devis est accepté, refusé ou annulé",
  regleSortie_endormi: "Se taire si le client a racheté entre-temps",
  regleUneFois: "Une personne n'entre qu'une fois par événement. Désinscrits, rebonds et adresses non confirmées sont écartés.",
  personnesAide: "Les 200 dernières entrées.",
  entreeLe: "Entrée le",
  prevuLe: "Prévu {date}",
  envoyeLe: "Envoyé le {date}",
  personneEncore: "Personne pour l'instant : le prochain événement les fera entrer.",
  activerPourCommencer: "Activez l'automatisation pour commencer.",
  supprimerAutoTitre: "Supprimer l'automatisation ?",
  supprimerAutoMessage: "« {nom} » et son historique seront retirés.",

  // Modèles
  sousModeles: "Des mises en page prêtes, et les vôtres",
  pointsDepart: "Points de départ",
  vosModeles: "Vos modèles",
  vosModelesAide: "Enregistrés depuis l'éditeur : mise en page, couleurs et blocs compris.",
  aucunModeleD: "Aucun modèle : dans l'éditeur, « Enregistrer comme modèle ».",
  modifierModele: "Modifier le modèle",
  supprimerModeleTitre: "Supprimer ce modèle ?",
  supprimerModeleMessage: "« {nom} » sera retiré. Les campagnes qui en sont parties ne changent pas.",
  depart_lettre: "Lettre d'information",
  departSujet_lettre: "Les nouvelles de {{entreprise}}",
  departApercu_lettre: "Ce qui a changé ce mois-ci",
  departTitre_lettre: "Les nouvelles du mois",
  departTexte_lettre: "Bonjour {{prenom}},\n\nVoici ce qui a changé chez nous ce mois-ci.",
  departBouton_lettre: "En savoir plus",
  depart_promo: "Promotion",
  departSujet_promo: "{{prenom}}, -20 % jusqu'à la fin du mois",
  departApercu_promo: "Stock limité, profitez-en vite",
  departTitre_promo: "Une offre rien que pour vous",
  departTexte_promo: "Bonjour {{prenom}},\n\nJusqu'à la fin du mois, profitez de nos meilleurs prix.",
  departBouton_promo: "J'en profite",
  depart_invitation: "Invitation",
  departSujet_invitation: "Vous êtes invité(e), {{prenom}}",
  departApercu_invitation: "Réservez la date",
  departTitre_invitation: "Vous êtes invité(e)",
  departTexte_invitation: "Bonjour {{prenom}},\n\nNous serions heureux de vous accueillir.",
  departGauche_invitation: "**Quand**\n[DATE ET HEURE]",
  departDroite_invitation: "**Où**\n[ADRESSE]",
  departBouton_invitation: "Je confirme ma présence",

  // Contacts
  sousContacts: "Ceux du CRM : un seul fichier pour toute l'entreprise",
  importerFichier: "Importer un fichier",
  listes: "Listes",
  tousContacts: "Tous les contacts",
  aucuneEtiquette: "Aucune étiquette.",
  contacts_tous: "Tous",
  contacts_engages: "Engagés",
  contacts_inactifs: "Inactifs 6 mois",
  contacts_rebonds: "Rebonds",
  contacts_desinscrits: "Désinscrits",
  contacts_aConfirmer: "À confirmer",
  contacts_sansEmail: "Sans e-mail",
  nChoisis: "{n} sélectionné(s)",
  retirerEtiquette: "Retirer « {e} »",
  jamaisEcrit: "Jamais écrit",
  scoreSur5: "Engagement {n} sur 5",
  engagementDetail: "{e} reçus, {o} ouverts, {c} cliqués",
  consentementDe: "{source} · {date}",
  reactiver: "Réactiver",
  reactiverTitre: "Réactiver cette adresse ?",
  reactiverMessage: "{email} avait rebondi. Ne la réactivez qu'après l'avoir corrigée ou vérifiée.",
  aucunContact: "Aucun contact : importez un fichier ou ajoutez des clients dans le CRM.",
  importerNom: "Importer « {nom} »",
  importInfo: "{n} lignes · séparateur « {sep} »",
  importAide: "Un fichier CSV (Excel : « Enregistrer sous » › CSV). Les contacts deviennent des fiches CRM.",
  import_1: "Fichier",
  import_2: "Colonnes",
  import_3: "Vérifier",
  importRegle: "Chaque ligne devient une fiche prospect du CRM, ou complète la fiche existante de la même adresse. Une personne désinscrite n'est jamais réabonnée.",
  choisirCsv: "Choisir un fichier CSV",
  fichierVide: "Fichier vide",
  fichierVideMessage: "Il faut une ligne d'en-têtes et au moins un contact.",
  colonneN: "Colonne « {nom} »",
  champPour: "Champ CRM pour {nom}",
  champ_ignorer: "— Ignorer —",
  champ_entreprise: "Entreprise",
  champ_nom: "Nom du contact",
  champ_email: "E-mail",
  champ_telephone: "Téléphone",
  champ_ville: "Ville",
  champ_secteur: "Secteur",
  champ_etiquettes: "Étiquettes",
  emailRequis: "Indiquez quelle colonne contient l'e-mail.",
  bilanNouveaux: "nouvelles fiches CRM (prospects)",
  bilanMisAJour: "fiches existantes complétées",
  bilanDoublons: "doublons dans le fichier",
  bilanInvalides: "adresses invalides",
  bilanDesinscrits: "désinscrits — jamais réabonnés",
  etiquetteImport: "Étiquette ajoutée à tous",
  sourceConsentement: "Origine du consentement",
  attestation: "J'atteste que ces personnes ont accepté de recevoir nos e-mails. Le consentement est enregistré sur chaque fiche, avec sa date et son origine.",
  importerN: "Importer {n} contacts",
  importTermine: "Import terminé",
  importTermineMessage: "{a} fiche(s) créée(s), {b} complétée(s).",
  importImpossible: "Import impossible",

  // Formulaire
  sousFormulaire: "Une page publique où vos visiteurs s'inscrivent — avec confirmation par e-mail",
  ouvrirFormulaire: "Ouvrir le formulaire",
  inscritsFormulaire: "Inscrits par le formulaire",
  confirmes: "Confirmés",
  enAttenteConfirmation: "En attente de confirmation",
  doubleOptin: "Double opt-in",
  doubleOptinD: "confirmation par e-mail obligatoire",
  lienFormulaire: "Lien du formulaire",
  lienFormulaireAide: "À partager sur WhatsApp, vos réseaux, votre signature d'e-mail ou un QR code.",
  regenerer: "Régénérer le lien",
  regenererAide: "Le lien circule trop ou reçoit des inscriptions de robots ?",
  regenererTitre: "Régénérer le lien du formulaire",
  regenererMessage: "L'ancien lien cessera aussitôt de fonctionner, partout où il a été partagé ou intégré. Il faudra mettre à jour votre site et vos messages avec le nouveau.",
  regenere: "Nouveau lien créé : l'ancien ne fonctionne plus.",
  surVotreSite: "Sur votre site",
  surVotreSiteAide: "Copiez l'un de ces codes dans votre site web.",
  boutonLien: "Un bouton qui ouvre le formulaire",
  formulaireIntegre: "Le formulaire intégré dans la page",
  boutonInscription: "Recevoir nos actualités",
  commentCaMarche: "Comment ça marche",
  formEtape1: "Le visiteur laisse son nom, son e-mail et coche l'accord.",
  formEtape2: "Il reçoit un e-mail de confirmation.",
  formEtape3: "En cliquant le lien, il devient un prospect joignable du CRM, consentement daté.",
  formEtape4: "L'automatisation « Bienvenue » peut lui écrire aussitôt.",
  formProtection: "Protégé contre les robots (champ piège, 6 envois par heure et par adresse IP). Une adresse déjà désinscrite n'est jamais réabonnée.",
};

const EN = {
  appNom: "Campaigns",
  verrou: "Sign in to run campaigns.",
  langueAuto: "Language: automatic",
  votreEntreprise: "Your company",
  joignablesN: "{n} reachable contacts",
  erreur: "Error",

  grpEnvoyer: "Send",
  grpAudience: "Audience",
  navAccueil: "Home",
  navCampagnes: "Campaigns",
  navAutomatisations: "Automations",
  navModeles: "Templates",
  navContacts: "Contacts & lists",
  navFormulaire: "Signup form",

  annuler: "Cancel",
  enregistrer: "Save",
  enregistre: "Saved",
  supprimer: "Delete",
  modifier: "Edit",
  dupliquer: "Duplicate",
  exporter: "Export",
  fermer: "Close",
  continuer: "Continue",
  retour: "Back",
  voir: "View",
  ajouter: "Add",
  envoyer: "Send",
  utiliser: "Use",
  copier: "Copy",
  copie: "Copied",
  gerer: "Manage",
  toutes: "All",
  reduire: "Show less",
  toutVoir: "Show all",
  toutCocher: "Select all",
  toutDecocher: "Clear selection",
  filtrer: "Filter",
  vue: "View",
  maintenant: "now",
  apercu: "Preview",
  objetVide: "(email subject)",
  sansNom: "Untitled",
  aucunResultat: "No results for these filters.",
  nom: "Name",
  email: "Email",
  telephone: "Phone",
  ville: "City",
  entreprise: "Company",
  contact: "Contact",
  statut: "Status",
  version: "Version",
  erreurColonne: "Error",
  nJours: "{n} days",
  nHeures: "{n} h",
  nMinutes: "about {n} min",
  nDestinataires: "{n} recipients",
  nContacts: "{n} contacts",
  nEnvoyes: "{n} sent",
  nFactures: "{n} invoices",
  afficherPlus: "Show more ({n} left)",
  affichesSur: "{a} of {b} shown",
  conseille: "recommended",
  actif: "On",
  active: "Active",
  enPause: "Paused",
  enCours: "In progress",
  envoyes: "Sent",
  sortis: "Exited",
  ouverture: "Open rate",
  clics: "Clicks",
  caAttribue: "Attributed revenue",
  campagne: "Campaign",
  destinataires: "Recipients",
  destinatairesMin: "recipients",
  message: "Message",
  objet: "Subject",
  reglages: "Settings",
  ficheCRM: "CRM record →",
  rebond: "Bounce",
  rebonds: "Bounces",
  desinscrit: "Unsubscribed",
  desinscrits: "Unsubscribed",
  desinscriptions: "Unsubscribes",
  aConfirmer: "Signup to confirm",
  nonConfirme: "Unconfirmed",
  sansEmail: "No valid email",
  doublons: "Duplicate addresses",
  auRepos: "Resting",
  ecartesMain: "Removed by hand",
  joignables: "Reachable",
  ouvert: "Opened",
  clique: "Clicked",
  echec: "Failed",
  sorti: "Exited",
  ouvertLe: "Opened at",
  cliqueLe: "Clicked at",
  erreurCsv: "Error",
  etiquette: "Tag",
  etiquettes: "Tags",
  engagement: "Engagement",
  consentement: "Consent",
  dernierAchat: "Last purchase",

  statut_brouillon: "Draft",
  statut_programmee: "Scheduled",
  statut_envoi: "Sending",
  statut_pause: "Paused",
  statut_terminee: "Sent",

  crm_tous: "All",
  crm_actif: "Active customers",
  crm_prospect: "Prospects",
  crm_inactif: "Inactive",

  origine_formulaire: "Signup form",
  origine_import: "Import",
  origine_crm: "CRM",

  source_crm: "CRM",
  source_facturation: "Invoicing",
  source_stock: "Inventory",

  bonjour: "Hello {nom}",
  sousAccueil: "{c} campaign(s) scheduled or sending, {a} automation(s) at work",
  nouvelleCampagne: "New campaign",
  nouvelleAuto: "New automation",
  kJoignables: "Reachable contacts",
  kJoignablesD: "+{n} new in 30 days",
  kEnvoyes: "Sent in 30 days",
  kEnvoyesD: "{n} campaign(s)",
  kOuverture: "Average open rate",
  kOuvertureD: "completed campaigns",
  kClicD: "{p} average click rate",
  kCA: "Attributed revenue (30 d)",
  kCAD: "invoices issued within 7 days of a click",
  aFaire: "To do",
  rienAFaire: "Nothing urgent: everything is up to date.",
  tAB: "A/B test decided: version {v} wins ({a}% vs {b}%)",
  tRebonds: "{n} address(es) hard-bounced",
  tRebondsD: "Suspended automatically: fix them in the CRM, then reactivate them",
  tProgrammees: "{n} scheduled campaign(s)",
  tRelance: "{n} people did not open",
  tAConfirmer: "{n} signup(s) awaiting confirmation",
  tAConfirmerD: "They will receive your campaigns once they click the confirmation link",
  tAuto: "Put your email marketing on autopilot",
  tAutoD: "Welcome, unsigned quote, thank-you after purchase… ready to switch on",
  tBrouillons: "{n} draft(s) to finish",
  corriger: "Fix",
  relancer: "Follow up",
  decouvrir: "Explore",
  reprendre: "Resume",
  campagnesRecentes: "Recent campaigns",
  aucuneCampagne: "No campaign yet",
  aucuneCampagneD: "Email your CRM customers, see who opens, who clicks and what it sells.",
  premiereCampagne: "Create my first campaign",
  testAB: "A/B test",
  aucuneAutoD: "No automation yet: switch on a recipe in two clicks.",
  santeListe: "List health",
  sansEmailOuAConfirmer: "No email or unconfirmed",
  gererContacts: "Manage contacts",

  sousCampagnes: "{n} campaign(s)",
  rechercherCampagne: "Search campaigns",
  onglet_toutes: "All",
  onglet_brouillon: "Drafts",
  onglet_programmee: "Scheduled",
  onglet_envoi: "Sending",
  onglet_terminee: "Sent",

  nomInterne: "Internal name",
  nomInterneExemple: "Back-to-school offer, annual closure…",
  etapes: "Steps",
  etape_audience: "Audience",
  etape_contenu: "Content",
  etape_envoi: "Send",
  continuerContenu: "Next: content",
  continuerEnvoi: "Next: send",
  nommerDabord: "Give it an internal name first",
  partirModele: "Start from a template",
  enregistrerModele: "Save as template",
  nomModele: "Template name",
  modeleEnregistre: "Template saved",
  modeleCourrier: "Mail template",
  aucunModele: "No saved template.",
  remplacerTitre: "Replace the content?",
  remplacerMessage: "The current blocks will be replaced by the template's.",
  remplacer: "Replace",
  envoyerTest: "Send a test",
  renvoyerTest: "Send the test again",
  testAide: "The test is sent exactly as your customers will receive it, to team members only (5 at most).",
  testEnvoye: "Test sent",
  testImpossible: "Test failed",
  testPartiel: "Test partly sent",
  testPartielMessage: "{n} address(es) skipped: tests only go to workspace members.",
  quitterTitre: "Leave without saving?",
  quitterMessage: "Changes to this campaign will be lost.",
  quitter: "Leave",
  bandeauRelance: "Follow-up of “{nom}”: only those who did not open will receive it. Change the subject — it is what did not convince.",
  seulAdmin: "Only an administrator can save and send a campaign.",
  brouillonEnregistre: "Draft saved",
  enregistrementImpossible: "Could not save",
  creeLe: "Created on {date}",

  aQui: "Who are you writing to?",
  aQuiAide: "Contacts come from the CRM. Each criterion narrows the audience.",
  listeFermee: "Closed list: {n} contacts chosen when the follow-up was created.",
  statutCRM: "CRM status",
  toutesEtiquettes: "All tags",
  ajouterEtiquette: "Add a tag",
  villes: "Cities",
  toutesVilles: "All cities",
  ajouterVille: "Add a city",
  secteurs: "Industries",
  tousSecteurs: "All industries",
  ajouterSecteur: "Add an industry",
  activite: "Activity",
  aRecuFacture: "Was invoiced in the",
  periodeAchat: "Purchase period",
  mois_1: "last 30 days",
  mois_3: "last 3 months",
  mois_6: "last 6 months",
  mois_12: "last 12 months",
  pression: "Pressure",
  ecarterRecents: "Skip people who got a campaign less than",
  delaiRepos: "Rest period",
  destinatairesAide: "Untick a contact to leave them out of this campaign only.",
  rechercherContact: "Name, email, city…",
  pasEmail: "No valid email",
  enRebond: "Bounced",
  auReposLigne: "Resting (recent campaign)",
  factureLe: "Invoiced on {date}",
  personne: "Nobody matches: widen the criteria, or add emails in the CRM.",
  audienceRetenue: "Audience",
  correspondent: "Match the criteria",
  dureeEnvoi: "Estimated sending time: about {duree} min, in small batches — to stay out of spam.",
  avantLancer: "Before sending",
  lancer_nom: "An internal name",
  lancer_audience: "An audience",
  lancer_sujet: "A subject",
  lancer_texte: "A message",
  lancer_cta: "Buttons with a valid link",
  lancer_ab: "Two different subjects for the A/B test",
  lancer_test: "A test received in your inbox",

  lienACompleter: "Link to fill in",
  vide_titre: "Empty heading — type it on the right",
  vide_texte: "Empty text — type it on the right",
  vide_image: "Choose an image: Cloud, computer or online address",
  vide_bouton: "Button without text — fill it in on the right",
  vide_produits: "Choose up to 6 Inventory items",
  vide_colonnes: "Empty columns",
  vide_promo: "Type a promo code",
  vide_separateur: "Divider",
  vide_reseaux: "Add your links: website, WhatsApp, Facebook…",
  vide_signature: "Empty signature",
  blocs: "Blocks",
  paletteAide: "Drag a block into the message, or click to add it below the selection.",
  bloc_titre: "Heading",
  bloc_texte: "Text",
  bloc_image: "Image",
  bloc_bouton: "Button",
  bloc_produits: "Products",
  bloc_colonnes: "2 columns",
  bloc_promo: "Promo code",
  bloc_separateur: "Divider",
  bloc_reseaux: "Social",
  bloc_signature: "Signature",
  blocAide_titre: "Big heading",
  blocAide_texte: "Bold, links, lists",
  blocAide_image: "From Cloud",
  blocAide_bouton: "Tracked link",
  blocAide_produits: "From Inventory, live prices",
  blocAide_colonnes: "Two texts side by side",
  blocAide_promo: "Code to copy",
  blocAide_separateur: "Line or space",
  blocAide_reseaux: "WhatsApp, Facebook…",
  blocAide_signature: "The closing words",
  planTravail: "Canvas",
  apercuReel: "Real preview",
  appareil: "Device",
  ordinateur: "Desktop",
  mobile: "Mobile",
  enTeteAuto: "Header: company logo and name",
  piedAuto: "Footer: legal notice and unsubscribe link, added automatically",
  feuilleVide: "Drop a first block here.",
  monter: "Move up",
  descendre: "Move down",
  versionA: "Version A",
  versionB: "Version B",
  nCaracteres: "{n} characters",
  objetExemple: "{{prenom}}, news from {{entreprise}}",
  objetBExemple: "Another way to say it",
  partTest: "Test share",
  delaiDecision: "Decide after",
  abExplication: "{part}% of the audience gets A or B (half each). After {heures} h, the version with the best open rate goes to everyone else.",
  texteApercu: "Preview text",
  texteApercuExemple: "The grey line after the subject in the inbox",
  inserer: "Insert:",
  var_client: "The company, or the contact's name",
  var_contact: "The person, when the record has a company",
  var_prenom: "The person's first name",
  var_ville: "The record's city",
  var_entreprise: "Your company's name",
  var_numero: "The quote or invoice number",
  var_annees: "Years of relationship",
  blocChoisi: "Selected block · {type}",
  aucunBloc: "No block selected",
  aucunBlocAide: "Click a block in the message to edit it.",
  couleur: "Color",
  couleurLibre: "Custom color",
  langueMessage: "Message language (footer, unsubscribe)",
  verifications: "Checks",
  verif_contenu: "A heading or a text",
  verif_contenu_ko: "Add a heading or a text",
  verif_boutons: "Buttons: valid text and link",
  verif_boutons_ko: "A button has no text or valid link",
  verif_images: "Images with alt text",
  verif_images_ko: "An image has no alt text",
  verif_poids: "Message size: {ko} KB",
  verif_poids_ko: "Heavy message ({ko} KB): Gmail will clip it",
  verif_desabo: "Unsubscribe link included",
  texte: "Text",
  taille: "Size",
  grand: "Large",
  moyen: "Medium",
  alignement: "Alignment",
  gauche: "Left",
  centre: "Center",
  texteAide: "**bold**, [link text](https://…), “- ” lines for a list",
  colonneGauche: "Left column",
  colonneDroite: "Right column",
  texteBouton: "Button text",
  lien: "Link",
  lienSuivi: "Every click is counted, link by link.",
  lienInvalide: "Invalid address: it must start with https://",
  codePromo: "Code",
  style: "Style",
  ligne: "Line",
  espace: "Space",
  reseau_site: "Website",
  reseau_whatsapp: "WhatsApp (number)",
  reseau_facebook: "Facebook",
  reseau_instagram: "Instagram",
  reseau_linkedin: "LinkedIn",
  choisirImage: "Choose an image",
  depuisCloud: "From Cloud",
  depuisOrdinateur: "From computer",
  imageCloud: "Cloud image: served to recipients through a signed address.",
  ouAdresseImage: "Or the address of an online image",
  texteAlternatif: "Alt text",
  texteAlternatifAide: "Read when images are blocked — and by screen readers.",
  lienImage: "Link when the image is clicked (optional)",
  afficherPrix: "Show prices",
  lienProduit: "Product link (optional)",
  chercherArticle: "Search an Inventory item",
  produitsAide: "Up to 6 products. Name and price come from Inventory.",
  produitsSansStock: "Install the Inventory app and create items to feature them here.",

  quand: "When?",
  maintenantEnvoi: "Now",
  departMinute: "Leaves within a minute",
  programmer: "Schedule",
  quandLisent: "When your customers read",
  creneau_demain8: "Tomorrow 8:00",
  creneau_lundi9: "Monday 9:00",
  creneau_mardi830: "Tuesday 8:30",
  dateHeure: "Send date and time",
  abEnvoi: "A/B test: {part}% of the audience first, then the best version to the rest after {heures} h.",
  recapitulatif: "Summary",
  liensSuivis: "Tracked links",
  dureeEstimee: "Sending time",
  annulableDepart: "Can be cancelled until it starts.",
  ilManque: "Missing: {liste}.",
  programmerCampagne: "Schedule campaign",
  lancerEnvoi: "Send now",
  programmerTitre: "Schedule the campaign?",
  lancerTitre: "Send the campaign?",
  lancerMessage: "“{nom}” will go to {n} recipient(s).",
  lancerDepart: "Starts {quand}, in small batches. Can be cancelled until then.",
  lancerMaintenant: "Starts within a minute, in small batches — to stay out of spam.",
  lancerAB: "A/B test on {part}% of the audience, decision after {heures} h.",
  lancer: "Send",
  lancementImpossible: "Could not send",
  campagneProgrammee: "Campaign scheduled",
  campagneLancee: "Campaign sent",

  campagneIntrouvable: "This campaign no longer exists.",
  departPrevu: "Starts {quand}",
  envoiEnCours: "Sending: {a} of {b} ({p}%)",
  envoyeeLe: "Sent {quand} {fin}",
  annulerProg: "Cancel schedule",
  annulerProgTitre: "Cancel the schedule?",
  annulerProgMessage: "“{nom}” goes back to draft: nothing will be sent.",
  mettrePause: "Pause",
  reprendreEnvoi: "Resume sending",
  relancerNonOuvreurs: "Follow up the {n} non-openers",
  progression: "Sending progress",
  versionN: "Version {v} · {n} sent",
  gagnant: "Winner",
  abEnCours: "Test running: the best version goes to the rest {heures} h after the last test email.",
  delivres: "Delivered",
  pctEnvoyes: "{p}% of recipients",
  ouverturesRobots: "instant (bot) opens excluded",
  pctOuvreurs: "{p}% of openers",
  carteClics: "Click map",
  carteClicsAide: "Share of clickers on each block's links",
  liens: "Links",
  aucunLien: "No link in this message.",
  ventesAttribuees: "Attributed sales · {montant}",
  ventesAide: "Invoices issued within 7 days of a click by the same customer",
  aucuneVente: "No invoice issued after a click yet.",
  nJoursApres: "{n} d after the click",
  leJourMeme: "same day",
  aTraiter: "Needs attention",
  rebondsDefinitifs: "Hard bounces",
  rebondsDefinitifsD: "Address does not exist: contact suspended, flagged on its CRM record.",
  rebondsTemporaires: "Soft bounces",
  rebondsTemporairesD: "Mailbox full or server busy: automatic retry in 6 h.",
  autresEchecs: "Other failures",
  reessayer: "Retry",
  desinscriptionsD: "Flagged in the CRM: no campaign will ever reach them again.",
  nouvelEssai: "Retry scheduled",
  nouvelEssaiMessage: "Failures go out again on the next pass.",
  ouverturesHeure: "Opens, hour by hour",
  pic: "Peak at {h}:00: {n} open(s)",
  ouverturesApres: "Opens will show here once sending starts.",
  aucuneOuverture: "No open recorded yet.",
  filtre_tous: "All",
  filtre_ouverts: "Opened",
  filtre_cliques: "Clicked",
  filtre_nonOuverts: "Not opened",
  filtre_echecs: "Failed",
  filtre_desinscrits: "Unsubscribed",
  reessaiPrevu: "Retry scheduled",
  enAttente: "Waiting",
  attendGagnant: "Waiting for the winning version",
  ouvertA: "Opened at {h}",
  cliqueA: "Clicked at {h}",
  delivreNonOuvert: "Delivered — not opened yet",
  personneCategorie: "Nobody in this category.",
  arreterTitre: "Stop and delete?",
  arreterMessage: "“{nom}” is being sent: the remaining emails will not go out.",
  supprimerCampagneTitre: "Delete this campaign?",
  supprimerCampagneMessage: "“{nom}” and its results will be removed.",

  sousAutos: "{n} active",
  vosAutos: "Your automations",
  automatisation: "Automation",
  recettes: "Ready-made recipes",
  recettesAide: "Each one listens to another CompanyOS app. Pick one, review the message, switch it on.",
  relancesFactures: "Unpaid invoice reminders live in the Mail app (automatic reminders): they are not duplicated here.",
  dejaN: "{n} already",
  recette_bienvenue: "Welcome",
  recette_devis: "Unsigned quote follow-up",
  recette_merci: "Thank you after purchase",
  recette_livraison: "Review after delivery",
  recette_endormi: "Lapsed customer",
  recette_anniversaire: "Relationship anniversary",
  recetteD_bienvenue: "New contact in the CRM or via the signup form",
  recetteD_devis: "Quote sent, still not accepted",
  recetteD_merci: "Invoice issued",
  recetteD_livraison: "Delivery recorded in Inventory",
  recetteD_endormi: "No purchase for 90 days",
  recetteD_anniversaire: "One more year since joining the CRM",
  autoIntrouvable: "This automation no longer exists.",
  activeDepuis: "Active since {date}",
  inactive: "Inactive — nothing is sent",
  scenario: "Workflow",
  personnes: "People",
  activer: "Activate",
  activerTitre: "Activate the automation?",
  activerMessage: "“{nom}” will now email the relevant customers automatically.",
  activerDetail: "Only events from now on count: nobody is caught up from the past.",
  etapeScenario_declencheur: "Trigger",
  etapeScenario_attendre: "Wait",
  etapeScenario_condition: "Condition",
  etapeScenario_email: "Email",
  decl_bienvenue: "A contact joins the CRM",
  decl_devis: "A quote is marked “Sent”",
  decl_merci: "An invoice is issued",
  decl_livraison: "An invoice is delivered (Inventory)",
  decl_endormi: "90 days without a purchase",
  decl_anniversaire: "Anniversary of joining the CRM",
  cond_devis: "Is the quote still pending?",
  cond_endormi: "Still no new purchase?",
  condSortie: "Otherwise: exit the workflow, no email",
  condIgnoree: "Condition off: the email goes out regardless",
  immediatement: "Immediately",
  puisCreneau: "Then the next business slot (Mon–Fri, 8:00–18:00)",
  sansCreneau: "At any time",
  emailDetail: "The message from the “Message” tab",
  nEntres: "{n} entered",
  nSortis: "{n} exited",
  pctOuverts: "{p} opened",
  nomAuto: "Name",
  delaiAvantEnvoi: "Delay before sending",
  regleOuvres: "Only send on business days, 8:00 – 18:00",
  regleSortie_devis: "Stay quiet if the quote is accepted, declined or cancelled",
  regleSortie_endormi: "Stay quiet if the customer bought again",
  regleUneFois: "A person enters only once per event. Unsubscribed, bounced and unconfirmed addresses are skipped.",
  personnesAide: "The latest 200 entries.",
  entreeLe: "Entered",
  prevuLe: "Due {date}",
  envoyeLe: "Sent on {date}",
  personneEncore: "Nobody yet: the next event will bring people in.",
  activerPourCommencer: "Activate the automation to start.",
  supprimerAutoTitre: "Delete the automation?",
  supprimerAutoMessage: "“{nom}” and its history will be removed.",

  sousModeles: "Ready-made layouts, and your own",
  pointsDepart: "Starting points",
  vosModeles: "Your templates",
  vosModelesAide: "Saved from the editor: layout, colors and blocks included.",
  aucunModeleD: "No template: in the editor, “Save as template”.",
  modifierModele: "Edit template",
  supprimerModeleTitre: "Delete this template?",
  supprimerModeleMessage: "“{nom}” will be removed. Campaigns created from it do not change.",
  depart_lettre: "Newsletter",
  departSujet_lettre: "News from {{entreprise}}",
  departApercu_lettre: "What changed this month",
  departTitre_lettre: "This month's news",
  departTexte_lettre: "Hello {{prenom}},\n\nHere is what changed with us this month.",
  departBouton_lettre: "Learn more",
  depart_promo: "Promotion",
  departSujet_promo: "{{prenom}}, 20% off until the end of the month",
  departApercu_promo: "Limited stock, don't wait",
  departTitre_promo: "An offer just for you",
  departTexte_promo: "Hello {{prenom}},\n\nUntil the end of the month, enjoy our best prices.",
  departBouton_promo: "Get the offer",
  depart_invitation: "Invitation",
  departSujet_invitation: "You're invited, {{prenom}}",
  departApercu_invitation: "Save the date",
  departTitre_invitation: "You're invited",
  departTexte_invitation: "Hello {{prenom}},\n\nWe would be delighted to welcome you.",
  departGauche_invitation: "**When**\n[DATE AND TIME]",
  departDroite_invitation: "**Where**\n[ADDRESS]",
  departBouton_invitation: "I'll be there",

  sousContacts: "Your CRM contacts: one list for the whole company",
  importerFichier: "Import a file",
  listes: "Lists",
  tousContacts: "All contacts",
  aucuneEtiquette: "No tags.",
  contacts_tous: "All",
  contacts_engages: "Engaged",
  contacts_inactifs: "Inactive 6 months",
  contacts_rebonds: "Bounced",
  contacts_desinscrits: "Unsubscribed",
  contacts_aConfirmer: "Unconfirmed",
  contacts_sansEmail: "No email",
  nChoisis: "{n} selected",
  retirerEtiquette: "Remove “{e}”",
  jamaisEcrit: "Never emailed",
  scoreSur5: "Engagement {n} out of 5",
  engagementDetail: "{e} received, {o} opened, {c} clicked",
  consentementDe: "{source} · {date}",
  reactiver: "Reactivate",
  reactiverTitre: "Reactivate this address?",
  reactiverMessage: "{email} had bounced. Only reactivate it once fixed or verified.",
  aucunContact: "No contacts: import a file or add customers in the CRM.",
  importerNom: "Import “{nom}”",
  importInfo: "{n} rows · separator “{sep}”",
  importAide: "A CSV file (Excel: “Save as” › CSV). Contacts become CRM records.",
  import_1: "File",
  import_2: "Columns",
  import_3: "Review",
  importRegle: "Each row becomes a CRM prospect, or completes the existing record with the same address. An unsubscribed person is never resubscribed.",
  choisirCsv: "Choose a CSV file",
  fichierVide: "Empty file",
  fichierVideMessage: "It needs a header row and at least one contact.",
  colonneN: "Column “{nom}”",
  champPour: "CRM field for {nom}",
  champ_ignorer: "— Skip —",
  champ_entreprise: "Company",
  champ_nom: "Contact name",
  champ_email: "Email",
  champ_telephone: "Phone",
  champ_ville: "City",
  champ_secteur: "Industry",
  champ_etiquettes: "Tags",
  emailRequis: "Say which column holds the email.",
  bilanNouveaux: "new CRM records (prospects)",
  bilanMisAJour: "existing records completed",
  bilanDoublons: "duplicates in the file",
  bilanInvalides: "invalid addresses",
  bilanDesinscrits: "unsubscribed — never resubscribed",
  etiquetteImport: "Tag added to everyone",
  sourceConsentement: "Consent source",
  attestation: "I confirm these people agreed to receive our emails. Consent is recorded on each record, with its date and source.",
  importerN: "Import {n} contacts",
  importTermine: "Import complete",
  importTermineMessage: "{a} record(s) created, {b} completed.",
  importImpossible: "Import failed",

  sousFormulaire: "A public page where visitors sign up — with email confirmation",
  ouvrirFormulaire: "Open the form",
  inscritsFormulaire: "Signed up via the form",
  confirmes: "Confirmed",
  enAttenteConfirmation: "Awaiting confirmation",
  doubleOptin: "Double opt-in",
  doubleOptinD: "email confirmation required",
  lienFormulaire: "Form link",
  lienFormulaireAide: "Share it on WhatsApp, social media, your email signature or a QR code.",
  regenerer: "Regenerate link",
  regenererAide: "Link spreading too far or getting bot sign-ups?",
  regenererTitre: "Regenerate the form link",
  regenererMessage: "The old link will stop working right away, everywhere it was shared or embedded. You'll need to update your website and messages with the new one.",
  regenere: "New link created: the old one no longer works.",
  surVotreSite: "On your website",
  surVotreSiteAide: "Paste one of these snippets into your website.",
  boutonLien: "A button that opens the form",
  formulaireIntegre: "The form embedded in the page",
  boutonInscription: "Get our news",
  commentCaMarche: "How it works",
  formEtape1: "The visitor leaves a name, an email and ticks the consent box.",
  formEtape2: "They receive a confirmation email.",
  formEtape3: "Clicking the link makes them a reachable CRM prospect, with dated consent.",
  formEtape4: "The “Welcome” automation can email them right away.",
  formProtection: "Protected against bots (honeypot field, 6 submissions per hour per IP). An unsubscribed address is never resubscribed.",
};

export const TEXTES = { fr: FR, en: EN };
