// CRM — les textes, en français et en anglais.
//
// La langue suit celle du système. Une clé absente en anglais retombe sur
// le français ; `crm.test.js` vérifie qu'il n'en manque aucune.

export const TEXTES = {
  fr: {
    appNom: "CRM",
    verrou: "Connectez-vous pour accéder à votre portefeuille.",
    chargement: "Chargement…",
    erreurChargement: "Le CRM n'a pas pu être chargé.",
    reessayer: "Réessayer",

    navJournee: "Ma journée",
    navPipeline: "Pipeline",
    navComptes: "Comptes",
    navContacts: "Contacts",
    navLeads: "Leads",
    navPrevisions: "Prévisions",
    navAgenda: "Agenda",
    navPlus: "Plus",
    vuesEnregistrees: "Vues enregistrées",
    nouvelleVue: "+ Enregistrer la vue",
    supprimerVue: "Supprimer la vue",

    rechercher: "Chercher un compte, un contact, une affaire…",
    nouveau: "+ Nouveau",
    nouveauCompte: "Nouveau compte",
    nouvelleAffaire: "Nouvelle affaire",
    nouveauContact: "Nouveau contact",
    nouvelleActivite: "Noter une activité",
    exporter: "Exporter (CSV)",
    retour: "Retour",
    enregistrer: "Enregistrer",
    annuler: "Annuler",
    supprimer: "Supprimer",
    modifier: "Modifier",
    fermer: "Fermer",
    tous: "Tous",
    aucun: "Aucun",
    personne: "Personne",
    moi: "Moi",

    // Ma journée
    bonjour: "Bonjour {nom}",
    resumeJour: "{retard} relance(s) en retard · {rdv} rendez-vous aujourd'hui",
    objectifMois: "Objectif du mois",
    objectifNonDefini: "Aucun objectif — fixez-le dans Prévisions",
    objectifReste: "{pct} % · il reste {jours} jours ouvrés",
    pipelinePondere: "Pipeline pondéré",
    pipelineOuvert: "{montant} ouverts",
    tauxGain: "Taux de gain (90 j)",
    cycleMoyen: "Cycle moyen : {n} jours",
    cycle: "Cycle de vente moyen",
    pasAssez: "Pas encore assez d'affaires closes",
    stagnent: "Affaires qui stagnent",
    stagnentDetail: "Sans activité depuis le seuil · {montant}",
    aFaireAujourdhui: "À faire",
    nbRetard: "{n} en retard",
    nbAujourdhui: "{n} aujourd'hui",
    rienAFaire: "Rien de prévu. Profitez-en pour relancer un compte silencieux.",
    voirPipeline: "Voir le pipeline",
    signaux: "Signaux des autres apps",
    aucunSignal: "Rien de nouveau dans les autres apps.",
    comptesSilencieux: "Comptes à réveiller",
    jamaisContacte: "Jamais contacté",
    ilYa: "il y a {n} j",
    marquerFait: "Marquer comme fait",
    appeler: "Appeler",
    ecrire: "E-mail",
    retardJ: "Retard {n} j",
    aujourdhui: "Aujourd'hui",
    demain: "Demain",

    // Pipeline
    filtreResponsable: "Responsable",
    seulementStagne: "Seulement ce qui stagne",
    tableau: "Tableau",
    liste: "Liste",
    ouvert: "Ouvert",
    pondere: "Pondéré",
    engage: "Engagé ce mois",
    gagne: "Gagné ce mois",
    colGagne: "Gagné",
    colEngage: "Engagé",
    objectif: "Objectif",
    pondereCourt: "pondéré {montant}",
    sansActivite: "Aucune activité prévue",
    joursSansActivite: "{n} j sans activité",
    legendeStagne: "Stagne : aucune activité depuis {n} jours ou plus (réglable par étape dans Prévisions)",
    legendeGagne: "Déposer sur « Gagnée » propose le devis, la facture ou le projet",
    legendePerdue: "Déposer sur « Perdue » demande le motif",
    deplacerVers: "Déplacer vers…",
    colAffaire: "Affaire",
    colCompte: "Compte",
    colEtape: "Étape",
    colMontant: "Montant",
    colCloture: "Clôture",
    colProchaine: "Prochaine activité",
    colResponsable: "Responsable",
    aucuneAffaire: "Aucune affaire ici.",

    // Étapes
    etape_contact: "Premier contact",
    etape_qualifie: "Qualifiée",
    etape_devis: "Devis envoyé",
    etape_negociation: "Négociation",
    etape_gagnee: "Gagnée",
    etape_perdue: "Perdue",

    // Statuts
    statut_prospect: "Prospect",
    statut_actif: "Client actif",
    statut_inactif: "Inactif",

    // Activités
    act_appel: "Appel",
    act_reunion: "Rendez-vous",
    act_email: "E-mail",
    act_note: "Note",
    act_tache: "Tâche",

    // Comptes
    colSante: "Santé",
    colCA: "CA 12 mois",
    colDernier: "Dernier contact",
    colVille: "Ville",
    colStatut: "Statut",
    nbComptes: "{n} compte(s)",
    aucunCompte: "Aucun compte ne correspond.",
    importerCsv: "Importer un CSV",
    importResume: "{crees} compte(s) créé(s), {doublons} doublon(s) ignoré(s).",

    // Fiche
    sante: "Santé du compte",
    sante_bon: "Bonne",
    sante_moyen: "À surveiller",
    sante_risque: "À risque",
    f_achats: "Achète depuis 12 mois",
    f_regulier: "Achats réguliers",
    f_croissance: "En croissance ({pct} %)",
    f_baisse: "En baisse ({pct} %)",
    f_jamaisContacte: "Jamais contacté",
    f_suivi: "Suivi récent",
    f_silence: "Silence depuis {jours} j",
    f_affaire: "Affaire en cours",
    f_retard: "Facture en retard",
    f_perdue: "Affaire perdue récemment",
    clientDepuis: "Client depuis {date}",
    responsable: "Responsable",
    whatsapp: "WhatsApp",
    itineraire: "Itinéraire",
    planifierRdv: "Planifier un RDV",
    creerDevis: "Créer un devis",
    ouvrirProjet: "Ouvrir un projet",
    ajouterCampagne: "Ajouter à une liste de campagne",
    viaCourrier: "via Courrier",
    viaAgenda: "Agenda",
    viaEditeur: "Éditeur de factures",
    viaProjets: "Projets",
    ongletActivite: "Activité",
    ongletContacts: "Contacts ({n})",
    ongletAffaires: "Affaires ({n})",
    ongletVentes: "Ventes",
    ongletInfos: "Informations",
    saisieRapide: "Noter un appel, une réunion… (« rappeler mardi » crée une relance)",
    saisieComprise: "Compris : {type}{echeance}",
    pour: " pour le {date}",
    filtreTout: "Tout",
    filtreEchanges: "Échanges",
    filtreVentes: "Ventes",
    filtrePaiements: "Paiements",
    filtreCampagnes: "Campagnes",
    filtreProjets: "Projets",
    aVenir: "À venir",
    historique: "Historique",
    historiqueFiche: "Historique",
    historiqueModifs: "Historique des modifications",
    comptesSupprimes: "Comptes supprimés",
    historiqueVide: "Aucun échange pour l'instant. Le premier appel commence ici.",
    reporter: "Reporter",
    fait: "Fait",
    chiffres: "Chiffres",
    sourceChiffres: "Facturation · Comptabilité",
    ca12: "CA 12 mois",
    du: "Dû",
    dontEchu: "dont {montant} échu",
    pipelineCompte: "Pipeline ouvert",
    nbAffaires: "{n} affaire(s)",
    delaiPaiement: "Délai de paiement",
    jours: "{n} j",
    contacts: "Contacts",
    ajouter: "+ Ajouter",
    aucunContact: "Aucun interlocuteur. Ajoutez le décideur en premier.",
    affaires: "Affaires",
    documents: "Devis et factures",
    aucunDocument: "Aucun document de facturation.",
    ouvrirDocument: "Ouvrir",
    supprimerCompte: "Supprimer le compte",
    supprimerCompteConfirme: "Supprimer « {nom} » ?",
    supprimerCompteDetail: "Ses affaires, contacts et activités partiront avec lui. Les documents de facturation restent : une pièce comptable ne s'efface pas.",

    ev_appel: "Appel",
    ev_reunion: "Rendez-vous",
    ev_email: "E-mail noté",
    ev_note: "Note",
    ev_tache: "Tâche faite",
    ev_affaire: "Affaire « {libelle} » — {etape}",
    ev_devis: "Devis {numero} — {montant}",
    ev_facture: "Facture {numero} — {montant}",
    ev_avoir: "Avoir {numero} — {montant}",
    ev_paiement: "Paiement reçu — {montant}",
    ev_courriel: "Courriel envoyé : « {sujet} »",
    ev_clic: "A cliqué dans la campagne « {nom} »",
    ev_ouverture: "A ouvert la campagne « {nom} »",
    ev_projet: "Projet : {titre}",
    app_crm: "CRM",
    app_facturation: "Facturation",
    app_courrier: "Courrier",
    app_campagnes: "Campagnes",
    app_projets: "Projets",
    app_comptabilite: "Comptabilité",

    // Rôles des contacts
    role_decideur: "Décideur",
    role_influenceur: "Influenceur",
    role_utilisateur: "Utilisateur",
    role_facturation: "Facturation",
    role_technique: "Technique",
    role_autre: "Autre",

    // Formulaires
    entreprise: "Entreprise",
    nomContact: "Nom",
    prenom: "Prénom",
    poste: "Poste",
    role: "Rôle",
    email: "E-mail",
    telephone: "Téléphone",
    ville: "Ville",
    adresse: "Adresse",
    secteur: "Secteur",
    statut: "Statut",
    source: "Source",
    etiquettes: "Étiquettes (séparées par des virgules)",
    notes: "Notes",
    libelle: "Libellé",
    compte: "Compte",
    choisirCompte: "— Choisir un compte —",
    montant: "Montant (FCFA)",
    probabilite: "Probabilité (%)",
    probabiliteAuto: "Selon l'étape ({n} %)",
    dateCloture: "Clôture prévue",
    contactPrincipal: "Contact principal",
    besoin: "Besoin exprimé",
    montantEstime: "Montant estimé",
    nomRequis: "Renseignez au moins un nom ou une entreprise.",
    libelleRequis: "Donnez un libellé à l'affaire et choisissez un compte.",
    doublonPossible: "Doublon possible",
    doublonDetail: "« {nom} » existe déjà ({raisons}).",
    raison_email: "même e-mail",
    raison_telephone: "même téléphone",
    raison_nom: "même nom",
    ouvrirExistant: "Ouvrir la fiche existante",
    creerQuandMeme: "Créer quand même",
    fusionner: "Fusionner",

    // Source
    source_formulaire: "Formulaire web",
    source_campagne: "Campagne",
    source_recommandation: "Recommandation",
    source_salon: "Salon",
    source_import: "Import CSV",
    source_appel: "Appel entrant",
    source_site: "Site web",
    source_autre: "Autre",

    // Perte / gain
    motifPerteTitre: "Pourquoi cette affaire est-elle perdue ?",
    motifPerteAide: "Le motif nourrit les rapports : on ne corrige que ce qu'on mesure.",
    motif_prix: "Prix trop élevé",
    motif_concurrent: "Concurrent choisi",
    motif_budget: "Pas de budget",
    motif_delai: "Délai",
    motif_besoin: "Besoin disparu",
    motif_silence: "Plus de réponse",
    motif_autre: "Autre",
    gagneeTitre: "Affaire gagnée 🎉",
    gagneeAide: "Et maintenant ?",
    gagneeFacture: "Préparer la facture",
    gagneeProjet: "Ouvrir le projet de livraison",
    gagneeRien: "Plus tard",
    compteDevenuClient: "{nom} passe en client actif.",

    // Activité / compte rendu
    compteRenduTitre: "Compte rendu d'appel",
    resultat: "Résultat",
    res_joint: "Joint",
    res_messagerie: "Messagerie",
    res_absent: "Pas de réponse",
    compteRendu: "Compte rendu",
    prochaineAction: "Prochaine action",
    prochaineActionAide: "Une affaire sans prochaine étape n'avance pas.",
    quand: "Quand",
    passerEtape: "Passer l'étape à",
    garderEtape: "Garder l'étape",
    type: "Type",
    resume: "Résumé",
    date: "Date",
    echeance: "Échéance",
    affaireLiee: "Affaire",
    aucuneAffaireLiee: "— Aucune —",
    rdvTitre: "Planifier un rendez-vous",
    rdvObjet: "Objet",
    heure: "Heure",
    lieu: "Lieu",
    rdvCree: "Rendez-vous ajouté à l'Agenda.",
    projetCree: "Projet « {nom} » créé dans Projets.",
    etiquetteTitre: "Ajouter à une liste de campagne",
    etiquetteAide: "Les listes des Campagnes sont les étiquettes des comptes.",
    etiquetteAjoutee: "Ajouté à la liste « {tag} ».",
    reporterTitre: "Reporter la tâche",

    // Contacts
    nbContacts: "{n} contact(s)",
    aucunContactListe: "Aucun contact. Les interlocuteurs s'ajoutent depuis la fiche d'un compte.",
    colNom: "Nom",
    colPoste: "Poste",
    colRole: "Rôle",

    // Leads
    nbLeads: "{n} à qualifier",
    filtreSource: "Source",
    filtreChauds: "Score ≥ 50",
    nonAttribues: "Non attribués",
    colLead: "Lead",
    colScore: "Score",
    colSignaux: "Signaux",
    colRecu: "Reçu",
    nonAttribue: "Non attribué",
    aucunLead: "Aucun lead à qualifier. Les inscrits du formulaire des Campagnes arrivent ici.",
    pourquoiScore: "Pourquoi ce score",
    r_formulaire: "Formulaire web rempli",
    r_recommandation: "Recommandation",
    r_rencontre: "Rencontré (salon, appel)",
    r_consentement: "Inscription confirmée",
    r_besoin: "Besoin exprimé",
    r_montant: "Montant estimé",
    r_clics: "{n} clic(s) dans les campagnes",
    r_ouvertures: "{n} ouverture(s) de campagne",
    r_email: "E-mail renseigné",
    r_telephone: "Téléphone renseigné",
    r_entreprise: "Entreprise renseignée",
    r_secteur: "Secteur cible ({secteur})",
    r_recent: "Échange cette semaine",
    qualifier: "Qualifier",
    convertir: "Convertir en compte + affaire",
    ecarter: "Écarter",
    attribuer: "Attribuer à",
    leadConverti: "Lead converti : l'affaire est dans le pipeline.",
    leadEcarte: "Lead écarté.",
    selectionnerLead: "Sélectionnez un lead pour le qualifier.",

    // Prévisions
    previsions: "Prévisions",
    mois: "Mois",
    nbAffairesCol: "Affaires",
    performance: "Performance (90 jours)",
    gagnees: "Gagnées",
    perdues: "Perdues",
    montantGagne: "Montant gagné",
    motifsPerte: "Motifs de perte",
    aucunePerte: "Aucune affaire perdue sur la période.",
    parSource: "Par source",
    reglages: "Réglages",
    objectifEquipe: "Objectif mensuel de l'équipe",
    objectifPerso: "Objectif mensuel — {nom}",
    seuilsStagnation: "Seuil de stagnation par étape (jours)",
    secteursCibles: "Secteurs cibles (pour le score des leads)",
    reglagesEnregistres: "Réglages enregistrés.",
    adminSeulement: "Seul un administrateur peut changer les objectifs.",

    // Vues
    vueNom: "Nom de la vue",
    vueCriteres: "Critères",
    caMin: "CA 12 mois minimum",
    sansContactJours: "Sans contact depuis (jours)",
    etiquette: "Étiquette",

    // Divers
    enregistre: "Enregistré.",
    supprime: "Supprimé.",
    clientAssigne: "Compte à suivre : {nom}",
    affaireAssignee: "Affaire à suivre : {libelle}",
    appAbsente: "L'application « {app} » n'est pas installée. Ajoutez-la depuis la Boutique.",
    sansNom: "Sans nom",
  },
  en: {
    appNom: "CRM",
    verrou: "Sign in to access your accounts.",
    chargement: "Loading…",
    erreurChargement: "The CRM could not be loaded.",
    reessayer: "Retry",

    navJournee: "My day",
    navPipeline: "Pipeline",
    navComptes: "Accounts",
    navContacts: "Contacts",
    navLeads: "Leads",
    navPrevisions: "Forecast",
    navAgenda: "Calendar",
    navPlus: "More",
    vuesEnregistrees: "Saved views",
    nouvelleVue: "+ Save view",
    supprimerVue: "Delete view",

    rechercher: "Search an account, a contact, a deal…",
    nouveau: "+ New",
    nouveauCompte: "New account",
    nouvelleAffaire: "New deal",
    nouveauContact: "New contact",
    nouvelleActivite: "Log an activity",
    exporter: "Export (CSV)",
    retour: "Back",
    enregistrer: "Save",
    annuler: "Cancel",
    supprimer: "Delete",
    modifier: "Edit",
    fermer: "Close",
    tous: "All",
    aucun: "None",
    personne: "Nobody",
    moi: "Me",

    bonjour: "Hello {nom}",
    resumeJour: "{retard} overdue follow-up(s) · {rdv} meeting(s) today",
    objectifMois: "Monthly target",
    objectifNonDefini: "No target — set it in Forecast",
    objectifReste: "{pct}% · {jours} working days left",
    pipelinePondere: "Weighted pipeline",
    pipelineOuvert: "{montant} open",
    tauxGain: "Win rate (90 d)",
    cycleMoyen: "Average cycle: {n} days",
    cycle: "Average sales cycle",
    pasAssez: "Not enough closed deals yet",
    stagnent: "Stalled deals",
    stagnentDetail: "No activity past the threshold · {montant}",
    aFaireAujourdhui: "To do",
    nbRetard: "{n} overdue",
    nbAujourdhui: "{n} today",
    rienAFaire: "Nothing planned. A good time to wake up a quiet account.",
    voirPipeline: "Open pipeline",
    signaux: "Signals from other apps",
    aucunSignal: "Nothing new in the other apps.",
    comptesSilencieux: "Accounts to wake up",
    jamaisContacte: "Never contacted",
    ilYa: "{n} d ago",
    marquerFait: "Mark as done",
    appeler: "Call",
    ecrire: "Email",
    retardJ: "{n} d late",
    aujourdhui: "Today",
    demain: "Tomorrow",

    filtreResponsable: "Owner",
    seulementStagne: "Stalled only",
    tableau: "Board",
    liste: "List",
    ouvert: "Open",
    pondere: "Weighted",
    engage: "Committed this month",
    gagne: "Won this month",
    colGagne: "Won",
    colEngage: "Committed",
    objectif: "Target",
    pondereCourt: "weighted {montant}",
    sansActivite: "No activity planned",
    joursSansActivite: "{n} d without activity",
    legendeStagne: "Stalled: no activity for {n} days or more (per-stage threshold in Forecast)",
    legendeGagne: "Dropping on “Won” offers the quote, invoice or project",
    legendePerdue: "Dropping on “Lost” asks for the reason",
    deplacerVers: "Move to…",
    colAffaire: "Deal",
    colCompte: "Account",
    colEtape: "Stage",
    colMontant: "Amount",
    colCloture: "Close date",
    colProchaine: "Next activity",
    colResponsable: "Owner",
    aucuneAffaire: "No deal here.",

    etape_contact: "First contact",
    etape_qualifie: "Qualified",
    etape_devis: "Quote sent",
    etape_negociation: "Negotiation",
    etape_gagnee: "Won",
    etape_perdue: "Lost",

    statut_prospect: "Prospect",
    statut_actif: "Active customer",
    statut_inactif: "Inactive",

    act_appel: "Call",
    act_reunion: "Meeting",
    act_email: "Email",
    act_note: "Note",
    act_tache: "Task",

    colSante: "Health",
    colCA: "12-month revenue",
    colDernier: "Last contact",
    colVille: "City",
    colStatut: "Status",
    nbComptes: "{n} account(s)",
    aucunCompte: "No matching account.",
    importerCsv: "Import CSV",
    importResume: "{crees} account(s) created, {doublons} duplicate(s) skipped.",

    sante: "Account health",
    sante_bon: "Good",
    sante_moyen: "Watch",
    sante_risque: "At risk",
    f_achats: "Bought in the last 12 months",
    f_regulier: "Regular purchases",
    f_croissance: "Growing ({pct}%)",
    f_baisse: "Declining ({pct}%)",
    f_jamaisContacte: "Never contacted",
    f_suivi: "Recently followed up",
    f_silence: "Silent for {jours} d",
    f_affaire: "Open deal",
    f_retard: "Overdue invoice",
    f_perdue: "Recently lost deal",
    clientDepuis: "Customer since {date}",
    responsable: "Owner",
    whatsapp: "WhatsApp",
    itineraire: "Directions",
    planifierRdv: "Schedule a meeting",
    creerDevis: "Create a quote",
    ouvrirProjet: "Open a project",
    ajouterCampagne: "Add to a campaign list",
    viaCourrier: "via Mail",
    viaAgenda: "Calendar",
    viaEditeur: "Invoice editor",
    viaProjets: "Projects",
    ongletActivite: "Activity",
    ongletContacts: "Contacts ({n})",
    ongletAffaires: "Deals ({n})",
    ongletVentes: "Sales",
    ongletInfos: "Details",
    saisieRapide: "Log a call, a meeting… (“call back tuesday” creates a follow-up)",
    saisieComprise: "Understood: {type}{echeance}",
    pour: " for {date}",
    filtreTout: "All",
    filtreEchanges: "Interactions",
    filtreVentes: "Sales",
    filtrePaiements: "Payments",
    filtreCampagnes: "Campaigns",
    filtreProjets: "Projects",
    aVenir: "Upcoming",
    historique: "History",
    historiqueFiche: "History",
    historiqueModifs: "Change history",
    comptesSupprimes: "Deleted accounts",
    historiqueVide: "No interaction yet. The first call starts here.",
    reporter: "Postpone",
    fait: "Done",
    chiffres: "Figures",
    sourceChiffres: "Invoicing · Accounting",
    ca12: "12-month revenue",
    du: "Due",
    dontEchu: "{montant} overdue",
    pipelineCompte: "Open pipeline",
    nbAffaires: "{n} deal(s)",
    delaiPaiement: "Payment delay",
    jours: "{n} d",
    contacts: "Contacts",
    ajouter: "+ Add",
    aucunContact: "No contact yet. Add the decision maker first.",
    affaires: "Deals",
    documents: "Quotes and invoices",
    aucunDocument: "No invoicing document.",
    ouvrirDocument: "Open",
    supprimerCompte: "Delete account",
    supprimerCompteConfirme: "Delete “{nom}”?",
    supprimerCompteDetail: "Its deals, contacts and activities go with it. Invoicing documents stay: an accounting record is never erased.",

    ev_appel: "Call",
    ev_reunion: "Meeting",
    ev_email: "Email logged",
    ev_note: "Note",
    ev_tache: "Task done",
    ev_affaire: "Deal “{libelle}” — {etape}",
    ev_devis: "Quote {numero} — {montant}",
    ev_facture: "Invoice {numero} — {montant}",
    ev_avoir: "Credit note {numero} — {montant}",
    ev_paiement: "Payment received — {montant}",
    ev_courriel: "Email sent: “{sujet}”",
    ev_clic: "Clicked in campaign “{nom}”",
    ev_ouverture: "Opened campaign “{nom}”",
    ev_projet: "Project: {titre}",
    app_crm: "CRM",
    app_facturation: "Invoicing",
    app_courrier: "Mail",
    app_campagnes: "Campaigns",
    app_projets: "Projects",
    app_comptabilite: "Accounting",

    role_decideur: "Decision maker",
    role_influenceur: "Influencer",
    role_utilisateur: "User",
    role_facturation: "Billing",
    role_technique: "Technical",
    role_autre: "Other",

    entreprise: "Company",
    nomContact: "Last name",
    prenom: "First name",
    poste: "Job title",
    role: "Role",
    email: "Email",
    telephone: "Phone",
    ville: "City",
    adresse: "Address",
    secteur: "Industry",
    statut: "Status",
    source: "Source",
    etiquettes: "Tags (comma separated)",
    notes: "Notes",
    libelle: "Name",
    compte: "Account",
    choisirCompte: "— Choose an account —",
    montant: "Amount (XOF)",
    probabilite: "Probability (%)",
    probabiliteAuto: "From stage ({n}%)",
    dateCloture: "Expected close",
    contactPrincipal: "Main contact",
    besoin: "Stated need",
    montantEstime: "Estimated amount",
    nomRequis: "Enter at least a name or a company.",
    libelleRequis: "Name the deal and choose an account.",
    doublonPossible: "Possible duplicate",
    doublonDetail: "“{nom}” already exists ({raisons}).",
    raison_email: "same email",
    raison_telephone: "same phone",
    raison_nom: "same name",
    ouvrirExistant: "Open existing record",
    creerQuandMeme: "Create anyway",
    fusionner: "Merge",

    source_formulaire: "Web form",
    source_campagne: "Campaign",
    source_recommandation: "Referral",
    source_salon: "Trade show",
    source_import: "CSV import",
    source_appel: "Inbound call",
    source_site: "Website",
    source_autre: "Other",

    motifPerteTitre: "Why was this deal lost?",
    motifPerteAide: "The reason feeds the reports: you only fix what you measure.",
    motif_prix: "Price too high",
    motif_concurrent: "Competitor chosen",
    motif_budget: "No budget",
    motif_delai: "Timing",
    motif_besoin: "Need disappeared",
    motif_silence: "No more answer",
    motif_autre: "Other",
    gagneeTitre: "Deal won 🎉",
    gagneeAide: "What next?",
    gagneeFacture: "Prepare the invoice",
    gagneeProjet: "Open the delivery project",
    gagneeRien: "Later",
    compteDevenuClient: "{nom} is now an active customer.",

    compteRenduTitre: "Call summary",
    resultat: "Outcome",
    res_joint: "Reached",
    res_messagerie: "Voicemail",
    res_absent: "No answer",
    compteRendu: "Summary",
    prochaineAction: "Next action",
    prochaineActionAide: "A deal without a next step does not move.",
    quand: "When",
    passerEtape: "Move stage to",
    garderEtape: "Keep stage",
    type: "Type",
    resume: "Summary",
    date: "Date",
    echeance: "Due date",
    affaireLiee: "Deal",
    aucuneAffaireLiee: "— None —",
    rdvTitre: "Schedule a meeting",
    rdvObjet: "Subject",
    heure: "Time",
    lieu: "Place",
    rdvCree: "Meeting added to the Calendar.",
    projetCree: "Project “{nom}” created in Projects.",
    etiquetteTitre: "Add to a campaign list",
    etiquetteAide: "Campaign lists are the accounts' tags.",
    etiquetteAjoutee: "Added to list “{tag}”.",
    reporterTitre: "Postpone task",

    nbContacts: "{n} contact(s)",
    aucunContactListe: "No contact. People are added from an account's record.",
    colNom: "Name",
    colPoste: "Job title",
    colRole: "Role",

    nbLeads: "{n} to qualify",
    filtreSource: "Source",
    filtreChauds: "Score ≥ 50",
    nonAttribues: "Unassigned",
    colLead: "Lead",
    colScore: "Score",
    colSignaux: "Signals",
    colRecu: "Received",
    nonAttribue: "Unassigned",
    aucunLead: "No lead to qualify. Campaign form sign-ups arrive here.",
    pourquoiScore: "Why this score",
    r_formulaire: "Filled in the web form",
    r_recommandation: "Referral",
    r_rencontre: "Met (trade show, call)",
    r_consentement: "Confirmed subscription",
    r_besoin: "Stated need",
    r_montant: "Estimated amount",
    r_clics: "{n} campaign click(s)",
    r_ouvertures: "{n} campaign open(s)",
    r_email: "Email provided",
    r_telephone: "Phone provided",
    r_entreprise: "Company provided",
    r_secteur: "Target industry ({secteur})",
    r_recent: "Contact this week",
    qualifier: "Qualify",
    convertir: "Convert to account + deal",
    ecarter: "Discard",
    attribuer: "Assign to",
    leadConverti: "Lead converted: the deal is in the pipeline.",
    leadEcarte: "Lead discarded.",
    selectionnerLead: "Select a lead to qualify it.",

    previsions: "Forecast",
    mois: "Month",
    nbAffairesCol: "Deals",
    performance: "Performance (90 days)",
    gagnees: "Won",
    perdues: "Lost",
    montantGagne: "Amount won",
    motifsPerte: "Loss reasons",
    aucunePerte: "No lost deal in the period.",
    parSource: "By source",
    reglages: "Settings",
    objectifEquipe: "Team monthly target",
    objectifPerso: "Monthly target — {nom}",
    seuilsStagnation: "Stall threshold per stage (days)",
    secteursCibles: "Target industries (for lead scoring)",
    reglagesEnregistres: "Settings saved.",
    adminSeulement: "Only an administrator can change targets.",

    vueNom: "View name",
    vueCriteres: "Criteria",
    caMin: "Minimum 12-month revenue",
    sansContactJours: "No contact for (days)",
    etiquette: "Tag",

    enregistre: "Saved.",
    supprime: "Deleted.",
    clientAssigne: "Account to follow: {nom}",
    affaireAssignee: "Deal to follow: {libelle}",
    appAbsente: "The “{app}” app is not installed. Add it from the Store.",
    sansNom: "Unnamed",
  },
};
