// Stock — les textes, en français et en anglais.
//
// La langue suit celle du système (réglage « Langue et région », automatique
// par défaut : celle que le navigateur annonce). Une clé absente en anglais
// retombe sur le français ; le test `stock.test.js` vérifie qu'il n'en
// manque aucune.

export const TEXTES = {
  fr: {
    appNom: "Stock",
    verrou: "Connectez-vous pour gérer le stock.",
    langueAuto: "Langue : automatique",
    appAbsente: "L'application « {app} » n'est pas installée. Ajoutez-la depuis la Boutique.",
    entrepotsCompte: "{n} entrepôt(s)",
    entrepot: "Entrepôt",
    tousEntrepots: "Tous les entrepôts",

    grpSuivre: "Suivre",
    grpCatalogue: "Catalogue",
    grpOperations: "Opérations",
    grpAnalyser: "Analyser",
    grpReglages: "Réglages",
    navTableau: "Tableau de bord",
    navArticles: "Articles",
    navCategories: "Catégories",
    navFournisseurs: "Fournisseurs",
    navMouvements: "Mouvements",
    navLivraisons: "Livraisons",
    navReappro: "Réapprovisionnement",
    navInventaires: "Inventaires",
    navScan: "Mode scan",
    navAnalyse: "Analyse",
    navEntrepots: "Entrepôts",
    navEtiquettes: "Étiquettes",

    // Communs
    annuler: "Annuler",
    enregistrer: "Enregistrer",
    supprimer: "Supprimer",
    modifier: "Modifier",
    valider: "Valider",
    fermer: "Fermer",
    continuer: "Continuer quand même",
    creer: "Créer",
    renommer: "Renommer",
    deplacer: "Déplacer",
    retirer: "Retirer",
    exporter: "Exporter",
    exporte: "Fichier exporté",
    fichierRange: "« {nom} » est rangé dans le dossier Stock du Cloud.",
    aucun: "Aucun",
    aucune: "Aucune",
    aucunResultat: "Aucun article ne correspond à ces filtres.",
    article: "Article",
    articleSupprime: "Article supprimé",
    articleIntrouvable: "Cet article n'existe plus.",
    articlesN: "{n} article(s)",
    reference: "Référence",
    designation: "Désignation",
    categorie: "Catégorie",
    fournisseur: "Fournisseur",
    unite: "Unité",
    quantite: "Quantité",
    date: "Date",
    type: "Type",
    lieu: "Lieu",
    lot: "Lot",
    peremption: "Péremption",
    prixUnitaire: "Prix unitaire",
    motif: "Motif",
    origine: "Motif / origine",
    montant: "Montant",
    valeur: "Valeur",
    total: "Total",
    etat: "État",
    statut: "Statut",
    classe: "Classe",
    pmp: "Coût moyen (PMP)",
    enStock: "En stock",
    disponible: "Disponible",
    reserve: "Réservé",
    enCommande: "En commande",
    emplacement: "Emplacement",
    emplacements: "Emplacements",
    de: "De",
    vers: "Vers",
    du: "Du",
    au: "au",
    nom: "Nom",
    code: "Code",
    adresse: "Adresse",
    contact: "Contact",
    telephone: "Téléphone",
    email: "E-mail",
    ville: "Ville",
    numero: "Numéro",
    jours: "{n} j",
    ht: "HT",
    ttc: "TTC",
    tva: "TVA (%)",
    facture: "Facture",
    archive: "Archivé",
    principal: "Principal",
    rechercheArticle: "Référence, désignation, code-barres…",
    sansCategorie: "Sans catégorie",
    toutesCategories: "Toutes les catégories",
    dormant: "Dormant",

    sens_entree: "Entrée",
    sens_sortie: "Sortie",
    sens_transfert: "Transfert",
    sens_inventaire: "Inventaire",
    etat_rupture: "Rupture",
    etat_alerte: "À commander",
    etat_ok: "OK",
    motifExemple_entree: "Réception, retour client…",
    motifExemple_sortie: "Vente, casse, échantillon…",
    motifExemple_transfert: "Réassort du magasin…",

    // Mouvements et alertes
    nouveauMouvement: "Nouveau mouvement",
    enStockPartout: "{q} {unite} en stock, tous entrepôts",
    transfertUnSeul: "Un seul entrepôt existe : créez-en un second dans Réglages › Entrepôts pour transférer.",
    lotAuto: "Automatique (premier périmé, premier sorti)",
    alerteTitre: "Stock bas : {article}",
    alerteMessage: "Il reste {q} {unite}, sous le point de commande ({seuil}).",
    insuffisantTitre: "Stock insuffisant",
    insuffisantMessage: "« {article} » : {dispo} disponible(s) ici, {demande} demandé(s). Le stock deviendra négatif.",
    supprimerMvtTitre: "Supprimer le mouvement",
    supprimerMvtMessage: "Supprimer le mouvement du {date} ({q}) ?",
    supprimerMvtDetail: "Le stock et le coût moyen seront recalculés sans lui.",
    noteCommande: "Préparée par le réapprovisionnement du Stock.",

    // Tableau de bord
    sousTableau: "{n} article(s) actif(s) · {m} mouvement(s)",
    kValeur: "Valeur du stock",
    kValeurD: "au coût moyen pondéré",
    kRupture: "En rupture",
    kPoint: "Sous le point de commande",
    kPointD: "{montant} à commander",
    kPerimes: "Lots à moins de 30 jours",
    kPerimesD: "{montant} à écouler",
    aFaire: "À faire ({n})",
    parUrgence: "par ordre d'urgence",
    rienAFaire: "Rien à faire : le stock est sous contrôle.",
    tReappro: "{n} article(s) à réapprovisionner",
    tReapproD: "Commandes suggérées : {montant}",
    preparerCommandes: "Préparer",
    tLivrer: "{n} facture(s) à livrer",
    livrer: "Livrer",
    tPerimes: "{n} lot(s) périment bientôt",
    voirLots: "Voir les lots",
    tReceptions: "{n} commande(s) fournisseur attendue(s)",
    ouvrirAchats: "Ouvrir les Achats",
    tCompter: "{n} article(s) de classe A à compter",
    tCompterD: "L'inventaire tournant compte les A chaque semaine.",
    compter: "Compter",
    tDormants: "{n} article(s) dormant(s)",
    tDormantsD: "{montant} immobilisés depuis 90 jours",
    examiner: "Examiner",
    derniersMouvements: "Derniers mouvements",
    toutHistorique: "Tout l'historique",
    aucunMouvement: "Aucun mouvement.",
    transferer: "Transférer",
    entrepotDetail: "{n} article(s) · {e} emplacement(s)",
    abcTitre: "Classement ABC",
    abcAide: "sur la valeur sortie en 90 jours",
    abcLigne: "{n} article(s) · {p} % de la valeur",

    // Articles
    sousArticles: "{n} affiché(s) sur {total}",
    nouvelArticle: "Nouvel article",
    filtre_tous: "Tous",
    filtre_rupture: "Rupture",
    filtre_alerte: "À commander",
    filtre_ok: "OK",
    filtre_dormant: "Dormants",
    trier: "Trier",
    tri_designation: "Nom (A→Z)",
    tri_stock: "Stock croissant",
    tri_valeur: "Valeur décroissante",
    tri_classe: "Classe ABC",
    voirArchives: "Voir les archivés",
    catalogueVide: "Le catalogue est vide. Créez votre premier article.",

    // Fiche article
    onglet_vue: "Vue d'ensemble",
    onglet_fiche: "Fiche",
    onglet_historique: "Historique",
    codeBarre: "Code-barres",
    suiviParLot: "suivi par lot",
    imprimerEtiquette: "Étiquette",
    entreeSortie: "Entrée / sortie",
    uniteEntrepots: "{unite} · {n} entrepôt(s)",
    reserveD: "{q} réservé(s) par la Facturation",
    rienReserve: "rien de réservé",
    couverture: "Couverture",
    consoD: "{q} sortie(s) par jour",
    pasDeVentes: "pas de sortie en 30 jours",
    valeurD: "valeur {v}",
    marge: "Marge",
    margeD: "vente {pv} TTC, TVA {tva} %",
    lotsTitre: "Lots",
    lotsAide: "premier périmé, premier sorti",
    sansLot: "Sans lot",
    perime: "Périmé",
    expireDans: "Expire dans {n} j",
    aEcoulerDabord: "À écouler d'abord",
    lotOk: "OK",
    aucunLot: "Aucun lot en stock.",
    pasSuiviLot: "Cet article n'est pas suivi par lot.",
    parEntrepot: "Par entrepôt",
    courbeTitre: "Niveau sur 30 jours",
    courbeAide: "ligne pointillée : point de commande ({point})",
    reapproTitre: "Réapprovisionnement",
    pSecurite: "Stock de sécurité",
    pSecuriteD: "vide = 2 jours de ventes",
    pDelai: "Délai fournisseur (j)",
    pDelaiD: "du bon de commande à la réception",
    pMultiple: "Multiple de commande",
    pMultipleD: "carton, palette…",
    pMax: "Stock maximum",
    pMaxD: "vide = 30 jours de ventes",
    pSeuil: "Seuil d'alerte",
    pSeuilD: "minimum si l'article ne se vend pas",
    pointCalc: "Point de commande : {n}",
    pointCalcD: "{conso}/jour × {delai} j de délai + {securite} de sécurité",
    pointSeuilD: "Pas de vente récente : le seuil d'alerte sert de point de commande.",
    dejaEnCommande: "{q} déjà en commande chez le fournisseur.",
    prixMarge: "Prix et marge",
    prixAchatFiche: "Prix d'achat",
    prixVente: "Prix de vente",
    prixVenteTtc: "Prix de vente TTC",
    margeUnitaire: "Marge unitaire",
    sorties30: "Sorties sur 30 jours",
    margeLigne: "Marge : {montant} par unité ({pct} %)",
    autresApps: "Dans les autres applications",
    ventesCaisse: "Vendu en caisse (30 j)",
    facturesEnCours: "Factures et devis en cours",
    commandesEnCours: "Commandes fournisseur en cours",
    identite: "Identité",
    marque: "Marque",
    emplacementHabituel: "Emplacement habituel",
    suiviLotLabel: "Suivre les lots et dates de péremption",
    description: "Description",
    image: "Image",
    ajouterImage: "Ajouter une image",
    changerImage: "Changer l'image",
    imageLourde: "Image trop lourde, même réduite.",
    designationRequise: "La désignation est obligatoire.",
    referencePrise: "La référence « {ref} » est déjà utilisée.",
    archiver: "Archiver",
    desarchiver: "Désarchiver",
    supprimerArticle: "Supprimer l'article",
    supprimerConfirm: "Supprimer définitivement « {nom} » ?",
    supprimerAvecHistorique: "Cet article a {n} mouvement(s) : le supprimer fausserait l'historique et la valeur du stock. L'archiver le retire des listes sans rien effacer.",
    historiqueAide: "Les mouvements créés par la Caisse, les Achats, une livraison ou un inventaire ne se suppriment pas d'ici.",

    // Réapprovisionnement
    sousReappro: "{n} article(s) chez {f} fournisseur(s)",
    creerCommandes: "Créer {n} commande(s) dans les Achats",
    reapproComment: "Comment c'est calculé",
    reapproExplication: "Un article est proposé quand son disponible (stock − réservé + en commande) passe sous son point de commande : ventes des 30 derniers jours × délai fournisseur + stock de sécurité. La quantité remonte au stock maximum, arrondie au multiple. Les commandes sont créées en brouillon : rien ne part sans relecture dans les Achats.",
    rienACommander: "Aucun article sous son point de commande.",
    sansFournisseur: "Sans fournisseur",
    sansFournisseurAide: "Ces articles n'ont pas de fournisseur : aucune commande ne peut être créée.",
    choisirFournisseur: "Indiquez le fournisseur dans la fiche de chaque article.",
    groupeAide: "{n} ligne(s) · {montant}",
    consoJour: "Sorties / jour",
    pointCommande: "Point de cde",
    aCommander: "À commander",
    couvertureJours: "couvre {n} j",
    sansVentes: "pas de vente récente",
    totalCommandes: "{n} commande(s) pour {montant}",
    lignesIgnorees: "{n} ligne(s) sans fournisseur ignorée(s)",
    commandesCreees: "{n} commande(s) créée(s)",
    commandesCreeesD: "{numeros} attendent votre relecture dans les Achats, en brouillon.",

    // Mouvements
    sousMouvements: "{n} mouvement(s)",
    rechercheMouvement: "Article, motif, lot…",
    voirPlus: "Voir plus ({n} restant(s))",

    // Livraisons
    sousLivraisons: "{n} facture(s) en attente de livraison",
    livrerDepuis: "Livrer depuis",
    ouvrirFacturation: "Ouvrir la Facturation",
    livraisonsComment: "Vendre n'est pas livrer",
    livraisonsExplication: "Une facture émise réserve ses articles. Livrer crée leurs sorties dans l'entrepôt choisi et libère la réservation. Les ventes en caisse, elles, sortent du stock immédiatement.",
    rienALivrer: "Toutes les factures sont livrées.",
    factureDu: "facture du {date}",
    stockInsuffisant: "Stock insuffisant",

    // Inventaires
    sousInventaires: "{n} session(s)",
    nouvelInventaire: "Nouvel inventaire",
    portee: "Que compter ?",
    portee_aCompter: "Les articles dus selon le planning ({n})",
    portee_categorie: "Une catégorie ({n})",
    portee_tout: "Tout le stock ({n})",
    commencer: "Commencer",
    sessions: "Sessions",
    comptes: "Comptés",
    ecartValorise: "Écart valorisé",
    statut_ouvert: "En cours",
    statut_valide: "Validé",
    aucunInventaire: "Aucun inventaire pour l'instant.",
    planning: "Planning tournant",
    planningAide: "compter souvent ce qui pèse lourd",
    planningLigne: "{n} à compter sur {total}",
    frequence: "tous les {n} jours",
    feuilleComptage: "Feuille de comptage",
    feuilleTitre: "Inventaire {numero}",
    feuilleNote: "Inscrivez la quantité comptée dans la colonne « Compté », puis saisissez-la dans CompanyOS.",
    valideLe: "Validé le {date}",
    progression: "Progression",
    comptesSur: "{n} compté(s) sur {total}",
    lignesEcart: "Lignes en écart",
    auPmp: "au coût moyen pondéré",
    emplacementsN: "{n} emplacement(s)",
    comptaTitre: "Envoyé à la Comptabilité",
    comptaTexte: "{sens} de {montant} proposée en écriture (6031 / 311), à valider dans la Comptabilité.",
    perte: "Perte",
    excedent: "Excédent",
    filtreInv_tous: "Tout",
    filtreInv_aCompter: "Reste à compter",
    filtreInv_ecarts: "Écarts",
    attendu: "Attendu",
    compte: "Compté",
    ecart: "Écart",
    cause: "Cause",
    cause_casse: "Casse",
    cause_vol: "Vol / démarque",
    cause_erreur: "Erreur de saisie",
    cause_peremption: "Péremption",
    cause_autre: "Autre",
    aucuneLigne: "Aucune ligne.",
    validerTitre: "Valider {numero}",
    validerMessage: "{n} ligne(s) comptée(s), {e} en écart, pour {montant}.",
    validerNonComptes: "{n} ligne(s) non comptée(s) gardent leur stock actuel.",
    validerCompta: "Les niveaux comptés deviennent le stock ; l'écart est proposé à la Comptabilité.",
    supprimerInvTitre: "Supprimer {numero}",
    supprimerInvMessage: "Le comptage en cours sera perdu. Le stock n'est pas modifié.",

    // Scan
    sousScan: "Douchette USB ou caméra du téléphone",
    mode: "Mode",
    mode_entree: "Recevoir",
    mode_sortie: "Sortir",
    mode_transfert: "Transférer",
    mode_compter: "Compter",
    inventaire: "Inventaire",
    aucunInventaireOuvert: "Aucun inventaire ouvert",
    scanSansInventaire: "Ouvrez d'abord un inventaire pour y reporter le comptage.",
    scannerIci: "Scannez ou tapez un code puis Entrée",
    camera: "Caméra",
    cameraRefusee: "La caméra n'est pas accessible.",
    codeInconnu: "Code inconnu : {code}",
    enStockIci: "{q} en stock ici",
    panierVide: "Scannez un article pour commencer.",
    panierTotal: "{n} article(s) · {q} unité(s)",
    validerScan_entree: "Enregistrer la réception",
    validerScan_sortie: "Enregistrer la sortie",
    validerScan_transfert: "Enregistrer le transfert",
    validerScan_compter: "Reporter dans l'inventaire",
    motifScan: "Mode scan",
    scanEnregistre: "{n} mouvement(s) enregistré(s).",
    scanReporte: "Comptage reporté dans {numero}.",

    // Analyse
    sousAnalyse: "Où dort l'argent, ce qui tourne, ce qui ne bouge plus",
    valorisationPdf: "Valorisation PDF",
    valorisationTitre: "Valorisation du stock",
    valorisationNote: "Valorisation au coût moyen pondéré, hors articles archivés.",
    auDate: "au {date}",
    detailArticles: "Détail par article",
    classeA: "Articles de classe A",
    kDormants: "Stock dormant",
    kReferences: "Références actives",
    enStockN: "{n} en stock",
    parCategorie: "Par catégorie",
    rienAValoriser: "Rien à valoriser.",
    topValeur: "Les 10 plus grosses valeurs",
    dormantsTitre: "Articles dormants",
    dormantsAide: "en stock, sans sortie depuis 90 jours",
    derniereSortie: "dernière sortie le {date}",
    jamaisSorti: "jamais sorti",
    aucunDormant: "Aucun article dormant.",

    // Catégories
    sousCategories: "{n} catégorie(s)",
    nouvelleCategorie: "Nouvelle catégorie",
    nouvelleSousCategorie: "Nouvelle sous-catégorie",
    renommerCategorie: "Renommer la catégorie",
    exempleCategorie: "Boissons",
    rangerCategorie: "Ranger « {nom} »",
    aLaRacine: "À la racine",
    supprimerCategorie: "Supprimer la catégorie",
    supprimerCategorieMessage: "Supprimer « {nom} » ?",
    supprimerCategorieDetail: "{s} sous-catégorie(s) supprimée(s) ; {n} article(s) passent en « sans catégorie ». Aucun article n'est supprimé.",
    aucuneCategorie: "Aucune catégorie. Elles rangent le catalogue et filtrent l'analyse.",

    // Fournisseurs
    sousFournisseurs: "{n} fournisseur(s)",
    nouveauFournisseur: "Nouveau fournisseur",
    delaiJours: "Délai de livraison (jours)",
    commandesOuvertes: "{n} commande(s) en cours",
    supprimerFournisseur: "Supprimer le fournisseur",
    supprimerFournisseurMessage: "Supprimer « {nom} » ?",
    supprimerFournisseurDetail: "{n} article(s) le citent : ils resteront sans fournisseur.",
    aucunFournisseur: "Aucun fournisseur. Ils servent au réapprovisionnement et aux Achats.",

    // Entrepôts
    sousEntrepots: "{n} entrepôt(s)",
    nouvelEntrepot: "Nouvel entrepôt",
    exempleEntrepot: "Dépôt Yopougon",
    emplacementsAide: "Un par ligne : allée, rayon, case…",
    supprimerEntrepot: "Supprimer l'entrepôt",
    supprimerEntrepotMessage: "Supprimer « {nom} » ?",
    entrepotNonVide: "« {nom} » contient encore du stock : transférez-le avant de supprimer l'entrepôt.",
    sansEmplacement: "Pas d'emplacement déclaré.",
    voirStockEntrepot: "Voir son stock",
    entrepotsComment: "Plusieurs lieux, un seul stock",
    entrepotsExplication: "Chaque mouvement porte son entrepôt. Le sélecteur en haut à gauche filtre tout l'écran ; le principal reçoit les ventes de la Caisse et les réceptions des Achats.",

    // Étiquettes
    sousEtiquettes: "{n} étiquette(s) · {p} planche(s)",
    genererEtiquettes: "Générer le PDF",
    toutCocher: "Tout cocher",
    toutDecocher: "Tout décocher",
    afficherPrix: "Afficher le prix",
    formatPlanche: "Planche A4, 3 × 8 étiquettes 70 × 37 mm, code 39",
    sansCodeBarre: "{n} article(s) sans code-barres ni référence : leur étiquette n'aura pas de code.",
    copies: "Copies",
  },

  en: {
    appNom: "Inventory",
    verrou: "Sign in to manage inventory.",
    langueAuto: "Language: automatic",
    appAbsente: "The “{app}” app is not installed. Add it from the Store.",
    entrepotsCompte: "{n} warehouse(s)",
    entrepot: "Warehouse",
    tousEntrepots: "All warehouses",

    grpSuivre: "Monitor",
    grpCatalogue: "Catalog",
    grpOperations: "Operations",
    grpAnalyser: "Analyze",
    grpReglages: "Settings",
    navTableau: "Dashboard",
    navArticles: "Items",
    navCategories: "Categories",
    navFournisseurs: "Suppliers",
    navMouvements: "Movements",
    navLivraisons: "Deliveries",
    navReappro: "Replenishment",
    navInventaires: "Stock counts",
    navScan: "Scan mode",
    navAnalyse: "Analysis",
    navEntrepots: "Warehouses",
    navEtiquettes: "Labels",

    annuler: "Cancel",
    enregistrer: "Save",
    supprimer: "Delete",
    modifier: "Edit",
    valider: "Validate",
    fermer: "Close",
    continuer: "Continue anyway",
    creer: "Create",
    renommer: "Rename",
    deplacer: "Move",
    retirer: "Remove",
    exporter: "Export",
    exporte: "File exported",
    fichierRange: "“{nom}” was saved to the Stock folder in Cloud.",
    aucun: "None",
    aucune: "None",
    aucunResultat: "No item matches these filters.",
    article: "Item",
    articleSupprime: "Deleted item",
    articleIntrouvable: "This item no longer exists.",
    articlesN: "{n} item(s)",
    reference: "SKU",
    designation: "Name",
    categorie: "Category",
    fournisseur: "Supplier",
    unite: "Unit",
    quantite: "Quantity",
    date: "Date",
    type: "Type",
    lieu: "Location",
    lot: "Batch",
    peremption: "Expiry",
    prixUnitaire: "Unit cost",
    motif: "Reason",
    origine: "Reason / source",
    montant: "Amount",
    valeur: "Value",
    total: "Total",
    etat: "Status",
    statut: "Status",
    classe: "Class",
    pmp: "Average cost",
    enStock: "On hand",
    disponible: "Available",
    reserve: "Reserved",
    enCommande: "On order",
    emplacement: "Bin",
    emplacements: "Bins",
    de: "From",
    vers: "To",
    du: "From",
    au: "to",
    nom: "Name",
    code: "Code",
    adresse: "Address",
    contact: "Contact",
    telephone: "Phone",
    email: "Email",
    ville: "City",
    numero: "Number",
    jours: "{n} d",
    ht: "excl. tax",
    ttc: "incl. tax",
    tva: "VAT (%)",
    facture: "Invoice",
    archive: "Archived",
    principal: "Main",
    rechercheArticle: "SKU, name, barcode…",
    sansCategorie: "Uncategorized",
    toutesCategories: "All categories",
    dormant: "Dead stock",

    sens_entree: "Receipt",
    sens_sortie: "Issue",
    sens_transfert: "Transfer",
    sens_inventaire: "Count",
    etat_rupture: "Out of stock",
    etat_alerte: "Reorder",
    etat_ok: "OK",
    motifExemple_entree: "Receipt, customer return…",
    motifExemple_sortie: "Sale, breakage, sample…",
    motifExemple_transfert: "Shop restock…",

    nouveauMouvement: "New movement",
    enStockPartout: "{q} {unite} on hand, all warehouses",
    transfertUnSeul: "Only one warehouse exists: create another in Settings › Warehouses to transfer.",
    lotAuto: "Automatic (first expired, first out)",
    alerteTitre: "Low stock: {article}",
    alerteMessage: "{q} {unite} left, below the reorder point ({seuil}).",
    insuffisantTitre: "Insufficient stock",
    insuffisantMessage: "“{article}”: {dispo} available here, {demande} requested. Stock will go negative.",
    supprimerMvtTitre: "Delete movement",
    supprimerMvtMessage: "Delete the movement of {date} ({q})?",
    supprimerMvtDetail: "Stock and average cost will be recomputed without it.",
    noteCommande: "Prepared by Inventory replenishment.",

    sousTableau: "{n} active item(s) · {m} movement(s)",
    kValeur: "Inventory value",
    kValeurD: "at weighted average cost",
    kRupture: "Out of stock",
    kPoint: "Below reorder point",
    kPointD: "{montant} to order",
    kPerimes: "Batches expiring < 30 days",
    kPerimesD: "{montant} to sell first",
    aFaire: "To do ({n})",
    parUrgence: "most urgent first",
    rienAFaire: "Nothing to do: inventory is under control.",
    tReappro: "{n} item(s) to replenish",
    tReapproD: "Suggested orders: {montant}",
    preparerCommandes: "Prepare",
    tLivrer: "{n} invoice(s) to deliver",
    livrer: "Deliver",
    tPerimes: "{n} batch(es) expiring soon",
    voirLots: "See batches",
    tReceptions: "{n} purchase order(s) expected",
    ouvrirAchats: "Open Purchasing",
    tCompter: "{n} class A item(s) to count",
    tCompterD: "Cycle counting checks A items every week.",
    compter: "Count",
    tDormants: "{n} dead stock item(s)",
    tDormantsD: "{montant} tied up for 90 days",
    examiner: "Review",
    derniersMouvements: "Latest movements",
    toutHistorique: "Full history",
    aucunMouvement: "No movements.",
    transferer: "Transfer",
    entrepotDetail: "{n} item(s) · {e} bin(s)",
    abcTitre: "ABC classification",
    abcAide: "by value issued over 90 days",
    abcLigne: "{n} item(s) · {p}% of value",

    sousArticles: "{n} shown of {total}",
    nouvelArticle: "New item",
    filtre_tous: "All",
    filtre_rupture: "Out of stock",
    filtre_alerte: "Reorder",
    filtre_ok: "OK",
    filtre_dormant: "Dead stock",
    trier: "Sort",
    tri_designation: "Name (A→Z)",
    tri_stock: "Lowest stock",
    tri_valeur: "Highest value",
    tri_classe: "ABC class",
    voirArchives: "Show archived",
    catalogueVide: "The catalog is empty. Create your first item.",

    onglet_vue: "Overview",
    onglet_fiche: "Details",
    onglet_historique: "History",
    codeBarre: "Barcode",
    suiviParLot: "batch tracked",
    imprimerEtiquette: "Label",
    entreeSortie: "Receive / issue",
    uniteEntrepots: "{unite} · {n} warehouse(s)",
    reserveD: "{q} reserved by Invoicing",
    rienReserve: "nothing reserved",
    couverture: "Coverage",
    consoD: "{q} issued per day",
    pasDeVentes: "no issues in 30 days",
    valeurD: "value {v}",
    marge: "Margin",
    margeD: "sells at {pv} incl. tax, VAT {tva}%",
    lotsTitre: "Batches",
    lotsAide: "first expired, first out",
    sansLot: "No batch",
    perime: "Expired",
    expireDans: "Expires in {n} d",
    aEcoulerDabord: "Sell first",
    lotOk: "OK",
    aucunLot: "No batch in stock.",
    pasSuiviLot: "This item is not batch tracked.",
    parEntrepot: "By warehouse",
    courbeTitre: "Level over 30 days",
    courbeAide: "dotted line: reorder point ({point})",
    reapproTitre: "Replenishment",
    pSecurite: "Safety stock",
    pSecuriteD: "empty = 2 days of sales",
    pDelai: "Supplier lead time (d)",
    pDelaiD: "from order to receipt",
    pMultiple: "Order multiple",
    pMultipleD: "case, pallet…",
    pMax: "Maximum stock",
    pMaxD: "empty = 30 days of sales",
    pSeuil: "Alert threshold",
    pSeuilD: "minimum if the item doesn't sell",
    pointCalc: "Reorder point: {n}",
    pointCalcD: "{conso}/day × {delai} d lead time + {securite} safety",
    pointSeuilD: "No recent sales: the alert threshold is used as the reorder point.",
    dejaEnCommande: "{q} already on order from the supplier.",
    prixMarge: "Price and margin",
    prixAchatFiche: "Purchase price",
    prixVente: "Selling price",
    prixVenteTtc: "Selling price incl. tax",
    margeUnitaire: "Unit margin",
    sorties30: "Issued over 30 days",
    margeLigne: "Margin: {montant} per unit ({pct}%)",
    autresApps: "In other apps",
    ventesCaisse: "Sold at POS (30 d)",
    facturesEnCours: "Open invoices and quotes",
    commandesEnCours: "Open purchase orders",
    identite: "Identity",
    marque: "Brand",
    emplacementHabituel: "Usual bin",
    suiviLotLabel: "Track batches and expiry dates",
    description: "Description",
    image: "Image",
    ajouterImage: "Add an image",
    changerImage: "Change image",
    imageLourde: "Image too large, even when reduced.",
    designationRequise: "Name is required.",
    referencePrise: "SKU “{ref}” is already in use.",
    archiver: "Archive",
    desarchiver: "Unarchive",
    supprimerArticle: "Delete item",
    supprimerConfirm: "Permanently delete “{nom}”?",
    supprimerAvecHistorique: "This item has {n} movement(s): deleting it would corrupt history and inventory value. Archiving hides it from lists without erasing anything.",
    historiqueAide: "Movements created by the POS, Purchasing, a delivery or a stock count cannot be deleted here.",

    sousReappro: "{n} item(s) from {f} supplier(s)",
    creerCommandes: "Create {n} order(s) in Purchasing",
    reapproComment: "How it's computed",
    reapproExplication: "An item is suggested when its availability (on hand − reserved + on order) falls below its reorder point: last 30 days of sales × supplier lead time + safety stock. The quantity tops up to the maximum stock, rounded to the order multiple. Orders are created as drafts: nothing is sent without review in Purchasing.",
    rienACommander: "No item below its reorder point.",
    sansFournisseur: "No supplier",
    sansFournisseurAide: "These items have no supplier: no order can be created.",
    choisirFournisseur: "Set the supplier on each item's details.",
    groupeAide: "{n} line(s) · {montant}",
    consoJour: "Issued / day",
    pointCommande: "Reorder pt",
    aCommander: "To order",
    couvertureJours: "covers {n} d",
    sansVentes: "no recent sales",
    totalCommandes: "{n} order(s) for {montant}",
    lignesIgnorees: "{n} line(s) without supplier skipped",
    commandesCreees: "{n} order(s) created",
    commandesCreeesD: "{numeros} await your review in Purchasing, as drafts.",

    sousMouvements: "{n} movement(s)",
    rechercheMouvement: "Item, reason, batch…",
    voirPlus: "Show more ({n} left)",

    sousLivraisons: "{n} invoice(s) awaiting delivery",
    livrerDepuis: "Deliver from",
    ouvrirFacturation: "Open Invoicing",
    livraisonsComment: "Selling is not delivering",
    livraisonsExplication: "An issued invoice reserves its items. Delivering issues them from the chosen warehouse and releases the reservation. POS sales, on the other hand, leave stock immediately.",
    rienALivrer: "All invoices are delivered.",
    factureDu: "invoice of {date}",
    stockInsuffisant: "Insufficient stock",

    sousInventaires: "{n} session(s)",
    nouvelInventaire: "New stock count",
    portee: "What to count?",
    portee_aCompter: "Items due per schedule ({n})",
    portee_categorie: "A category ({n})",
    portee_tout: "All stock ({n})",
    commencer: "Start",
    sessions: "Sessions",
    comptes: "Counted",
    ecartValorise: "Variance value",
    statut_ouvert: "In progress",
    statut_valide: "Validated",
    aucunInventaire: "No stock count yet.",
    planning: "Cycle count schedule",
    planningAide: "count often what matters most",
    planningLigne: "{n} due of {total}",
    frequence: "every {n} days",
    feuilleComptage: "Count sheet",
    feuilleTitre: "Stock count {numero}",
    feuilleNote: "Write the counted quantity in the “Counted” column, then enter it in CompanyOS.",
    valideLe: "Validated on {date}",
    progression: "Progress",
    comptesSur: "{n} counted of {total}",
    lignesEcart: "Lines with variance",
    auPmp: "at weighted average cost",
    emplacementsN: "{n} bin(s)",
    comptaTitre: "Sent to Accounting",
    comptaTexte: "{sens} of {montant} proposed as a journal entry (6031 / 311), to be validated in Accounting.",
    perte: "Loss",
    excedent: "Surplus",
    filtreInv_tous: "All",
    filtreInv_aCompter: "Left to count",
    filtreInv_ecarts: "Variances",
    attendu: "Expected",
    compte: "Counted",
    ecart: "Variance",
    cause: "Cause",
    cause_casse: "Breakage",
    cause_vol: "Theft / shrinkage",
    cause_erreur: "Entry error",
    cause_peremption: "Expired",
    cause_autre: "Other",
    aucuneLigne: "No lines.",
    validerTitre: "Validate {numero}",
    validerMessage: "{n} line(s) counted, {e} with variance, for {montant}.",
    validerNonComptes: "{n} uncounted line(s) keep their current stock.",
    validerCompta: "Counted levels become the stock; the variance is proposed to Accounting.",
    supprimerInvTitre: "Delete {numero}",
    supprimerInvMessage: "The count in progress will be lost. Stock is not changed.",

    sousScan: "USB scanner or phone camera",
    mode: "Mode",
    mode_entree: "Receive",
    mode_sortie: "Issue",
    mode_transfert: "Move",
    mode_compter: "Count",
    inventaire: "Stock count",
    aucunInventaireOuvert: "No open stock count",
    scanSansInventaire: "Open a stock count first to record counts into it.",
    scannerIci: "Scan or type a code, then Enter",
    camera: "Camera",
    cameraRefusee: "The camera is not available.",
    codeInconnu: "Unknown code: {code}",
    enStockIci: "{q} on hand here",
    panierVide: "Scan an item to start.",
    panierTotal: "{n} item(s) · {q} unit(s)",
    validerScan_entree: "Save receipt",
    validerScan_sortie: "Save issue",
    validerScan_transfert: "Save transfer",
    validerScan_compter: "Add to stock count",
    motifScan: "Scan mode",
    scanEnregistre: "{n} movement(s) saved.",
    scanReporte: "Count added to {numero}.",

    sousAnalyse: "Where the money sleeps, what moves, what doesn't",
    valorisationPdf: "Valuation PDF",
    valorisationTitre: "Inventory valuation",
    valorisationNote: "Valued at weighted average cost, archived items excluded.",
    auDate: "as of {date}",
    detailArticles: "Detail by item",
    classeA: "Class A items",
    kDormants: "Dead stock",
    kReferences: "Active SKUs",
    enStockN: "{n} in stock",
    parCategorie: "By category",
    rienAValoriser: "Nothing to value.",
    topValeur: "Top 10 by value",
    dormantsTitre: "Dead stock",
    dormantsAide: "on hand, no issue for 90 days",
    derniereSortie: "last issued on {date}",
    jamaisSorti: "never issued",
    aucunDormant: "No dead stock.",

    sousCategories: "{n} categories",
    nouvelleCategorie: "New category",
    nouvelleSousCategorie: "New subcategory",
    renommerCategorie: "Rename category",
    exempleCategorie: "Beverages",
    rangerCategorie: "Move “{nom}”",
    aLaRacine: "At the top level",
    supprimerCategorie: "Delete category",
    supprimerCategorieMessage: "Delete “{nom}”?",
    supprimerCategorieDetail: "{s} subcategories deleted; {n} item(s) become uncategorized. No item is deleted.",
    aucuneCategorie: "No categories. They organize the catalog and filter the analysis.",

    sousFournisseurs: "{n} supplier(s)",
    nouveauFournisseur: "New supplier",
    delaiJours: "Lead time (days)",
    commandesOuvertes: "{n} open order(s)",
    supprimerFournisseur: "Delete supplier",
    supprimerFournisseurMessage: "Delete “{nom}”?",
    supprimerFournisseurDetail: "{n} item(s) reference it: they will have no supplier.",
    aucunFournisseur: "No suppliers. They drive replenishment and Purchasing.",

    sousEntrepots: "{n} warehouse(s)",
    nouvelEntrepot: "New warehouse",
    exempleEntrepot: "Yopougon depot",
    emplacementsAide: "One per line: aisle, shelf, bin…",
    supprimerEntrepot: "Delete warehouse",
    supprimerEntrepotMessage: "Delete “{nom}”?",
    entrepotNonVide: "“{nom}” still holds stock: transfer it before deleting the warehouse.",
    sansEmplacement: "No bins defined.",
    voirStockEntrepot: "See its stock",
    entrepotsComment: "Several places, one inventory",
    entrepotsExplication: "Every movement carries its warehouse. The selector at the top left filters every screen; the main warehouse receives POS sales and Purchasing receipts.",

    sousEtiquettes: "{n} label(s) · {p} sheet(s)",
    genererEtiquettes: "Generate PDF",
    toutCocher: "Select all",
    toutDecocher: "Clear all",
    afficherPrix: "Show price",
    formatPlanche: "A4 sheet, 3 × 8 labels 70 × 37 mm, Code 39",
    sansCodeBarre: "{n} item(s) without barcode or SKU: their label will have no code.",
    copies: "Copies",
  },
};
