// Textes de l'app Automatisations (fr / en).

export const TEXTES = {
  fr: {
    titre: "Automatisations",
    sousTitre: "Quand quelque chose arrive dans une app, CompanyOS agit dans une autre.",
    reserve: "Réservé aux administrateurs",
    reserveAide: "Une automatisation agit pour tout l'espace : seuls les administrateurs peuvent la configurer.",
    vueListe: "Mes automatisations",
    vueRecettes: "Recettes",
    nouvelle: "Nouvelle automatisation",
    aucune: "Aucune automatisation",
    aucuneAide: "Partez d'une recette prête à l'emploi, ou créez la vôtre.",
    voirRecettes: "Voir les recettes",
    active: "Active",
    enPause: "En pause",
    executions: "{n} exécution(s)",
    echecs: "{n} en échec",
    jamais: "Jamais exécutée",
    derniere: "Dernière : {quand}",
    modifier: "Modifier",
    historique: "Historique",
    supprimer: "Supprimer",
    supprimerTitre: "Supprimer l'automatisation",
    supprimerMsg: "« {nom} » ne s'exécutera plus. Son historique sera effacé.",
    utiliser: "Utiliser",
    dejaUtilisee: "Déjà active",
    recettesAide: "Des automatisations éprouvées, à activer en un clic puis à ajuster.",
    // Éditeur
    retour: "Retour",
    nom: "Nom",
    nomAide: "Ce que fait l'automatisation, en quelques mots.",
    quand: "Quand",
    collection: "Dans",
    autreCollection: "Autre (app du Studio)…",
    module: "Application",
    collectionLibre: "Collection",
    evenement: "Il se passe",
    ev_creation: "Une fiche est créée",
    ev_modification: "Une fiche est modifiée",
    ev_suppression: "Une fiche est supprimée",
    champSurveille: "Seulement si ce champ change",
    nimporteQuelChamp: "N'importe quel champ",
    lier: "Lire aussi la fiche liée",
    lierAide: "Ex. le règlement pointe vers sa facture : {{lie.numero}} devient utilisable.",
    lierChamp: "Champ du lien",
    si: "Si",
    toutes: "Toutes les conditions",
    uneSeule: "Au moins une",
    sansCondition: "Sans condition : à chaque fois.",
    ajouterCondition: "Ajouter une condition",
    champ: "Champ",
    valeur: "Valeur",
    alors: "Alors",
    ajouterAction: "Ajouter une action",
    op_egal: "est égal à",
    op_different: "est différent de",
    op_contient: "contient",
    op_superieur: "est supérieur à",
    op_inferieur: "est inférieur à",
    op_vide: "est vide",
    "op_non-vide": "n'est pas vide",
    op_change: "change",
    op_devient: "devient",
    act_notifier: "Prévenir quelqu'un",
    act_creer: "Créer une fiche",
    act_modifier: "Modifier cette fiche",
    act_tache: "Créer une tâche dans Projets",
    act_courriel: "Envoyer un courriel (membres)",
    act_webhook: "Appeler un webhook",
    dest: "À qui",
    dest_champ: "La personne du champ",
    dest_auteur: "L'auteur du changement",
    dest_admins: "Les administrateurs",
    dest_membres: "Des membres choisis",
    dest_tous: "Tout l'espace",
    titreNotif: "Titre",
    message: "Message",
    sujet: "Sujet",
    texte: "Texte",
    cible: "Dans",
    champs: "Champs",
    ajouterChamp: "Ajouter un champ",
    tableau: "Tableau",
    premierTableau: "Le premier tableau",
    assigne: "Assigner à la personne du champ",
    personne: "Personne",
    echeance: "Échéance",
    description: "Description",
    url: "Adresse https://",
    secret: "Secret de signature",
    secretAide: "Chaque appel porte l'en-tête X-CompanyOS-Signature : HMAC-SHA256 de « horodatage.corps » avec ce secret.",
    secretApres: "Le secret de signature s'affiche une fois l'automatisation enregistrée.",
    balises: "Balises",
    balisesAide: "Cliquez pour copier, puis collez dans un texte : elles seront remplacées par les valeurs de la fiche.",
    copie: "Copié : {b}",
    essayer: "Essayer à blanc",
    essaiAide: "Sur la dernière fiche de la collection. Rien n'est exécuté.",
    essaiOui: "Sur cette fiche, l'automatisation s'exécuterait.",
    essaiNon: "Sur cette fiche, l'automatisation ne s'exécuterait pas.",
    essaiVide: "Aucune fiche dans cette collection pour essayer.",
    enregistrer: "Enregistrer",
    enregistree: "Automatisation enregistrée",
    activee: "Automatisation activée",
    pausee: "Automatisation en pause",
    retirer: "Retirer",
    erreurs: "À corriger",
    // Historique
    histTitre: "Dernières exécutions",
    histVide: "Pas encore d'exécution.",
    ok: "Réussie",
    erreur: "En échec",
    fiche: "Fiche",
    par: "par {nom}",
  },
  en: {
    titre: "Automations",
    sousTitre: "When something happens in one app, CompanyOS acts in another.",
    reserve: "Administrators only",
    reserveAide: "An automation acts for the whole workspace: only administrators can set it up.",
    vueListe: "My automations",
    vueRecettes: "Recipes",
    nouvelle: "New automation",
    aucune: "No automations",
    aucuneAide: "Start from a ready-made recipe, or build your own.",
    voirRecettes: "Browse recipes",
    active: "Active",
    enPause: "Paused",
    executions: "{n} run(s)",
    echecs: "{n} failed",
    jamais: "Never run",
    derniere: "Last: {quand}",
    modifier: "Edit",
    historique: "History",
    supprimer: "Delete",
    supprimerTitre: "Delete automation",
    supprimerMsg: "“{nom}” will stop running. Its history will be erased.",
    utiliser: "Use",
    dejaUtilisee: "Already active",
    recettesAide: "Proven automations: turn one on in a click, then adjust it.",
    retour: "Back",
    nom: "Name",
    nomAide: "What the automation does, in a few words.",
    quand: "When",
    collection: "In",
    autreCollection: "Other (Studio app)…",
    module: "App",
    collectionLibre: "Collection",
    evenement: "This happens",
    ev_creation: "A record is created",
    ev_modification: "A record is updated",
    ev_suppression: "A record is deleted",
    champSurveille: "Only if this field changes",
    nimporteQuelChamp: "Any field",
    lier: "Also read the linked record",
    lierAide: "E.g. a payment points to its invoice: {{lie.numero}} becomes available.",
    lierChamp: "Link field",
    si: "If",
    toutes: "All conditions",
    uneSeule: "At least one",
    sansCondition: "No condition: every time.",
    ajouterCondition: "Add a condition",
    champ: "Field",
    valeur: "Value",
    alors: "Then",
    ajouterAction: "Add an action",
    op_egal: "equals",
    op_different: "is not",
    op_contient: "contains",
    op_superieur: "is greater than",
    op_inferieur: "is less than",
    op_vide: "is empty",
    "op_non-vide": "is not empty",
    op_change: "changes",
    op_devient: "becomes",
    act_notifier: "Notify someone",
    act_creer: "Create a record",
    act_modifier: "Update this record",
    act_tache: "Create a task in Projects",
    act_courriel: "Send an email (members)",
    act_webhook: "Call a webhook",
    dest: "To",
    dest_champ: "The person in field",
    dest_auteur: "Whoever made the change",
    dest_admins: "Administrators",
    dest_membres: "Selected members",
    dest_tous: "Whole workspace",
    titreNotif: "Title",
    message: "Message",
    sujet: "Subject",
    texte: "Text",
    cible: "In",
    champs: "Fields",
    ajouterChamp: "Add a field",
    tableau: "Board",
    premierTableau: "The first board",
    assigne: "Assign to the person in field",
    personne: "Person",
    echeance: "Due date",
    description: "Description",
    url: "https:// address",
    secret: "Signing secret",
    secretAide: "Each call carries an X-CompanyOS-Signature header: HMAC-SHA256 of “timestamp.body” with this secret.",
    secretApres: "The signing secret shows once the automation is saved.",
    balises: "Tags",
    balisesAide: "Click to copy, then paste into a text: they are replaced with the record's values.",
    copie: "Copied: {b}",
    essayer: "Dry run",
    essaiAide: "On the latest record of the collection. Nothing is executed.",
    essaiOui: "On this record, the automation would run.",
    essaiNon: "On this record, the automation would not run.",
    essaiVide: "No record in this collection to try with.",
    enregistrer: "Save",
    enregistree: "Automation saved",
    activee: "Automation turned on",
    pausee: "Automation paused",
    retirer: "Remove",
    erreurs: "To fix",
    histTitre: "Latest runs",
    histVide: "No runs yet.",
    ok: "Succeeded",
    erreur: "Failed",
    fiche: "Record",
    par: "by {nom}",
  },
};
